image: Visual Studio 2019

environment:
  WXWIN: '%APPVEYOR_BUILD_FOLDER%\wxWidgets'
  ICUWIN: '%APPVEYOR_BUILD_FOLDER%\icu'

install:
  # Set paths to dependencies (based on architecture)
  - cmd: set PYTHON_ROOT=C:\python37-x64
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson and ninja
  - cmd: pip install ninja meson
  # download wxWidgets
  - cmd: mkdir %WXWIN%
  - cmd: chdir %WXWIN%
  - cmd: curl -L -o wxWidgets.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.7z
  - cmd: 7z x wxWidgets.7z
  # build wxWidgets
  - cmd: msbuild /m %WXWIN%\build\msw\wx_vc16.sln "/p:Configuration=DLL Release;Platform=Win32;PlatformToolset=v142" /target:adv,base,core,html,net,qa,wxexpat,wxjpeg,wxpng,wxtiff,wxzlib,xml /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # Download ICU
  - cmd: mkdir %ICUWIN%
  - cmd: chdir %ICUWIN%
  - cmd: curl -L -o icu.zip https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-Win64-MSVC2017.zip
  - cmd: 7z x icu.zip
  # Set up the build environment
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64'
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_71_0

build_script:
  - cmd: meson --backend=ninja -Dwx_path=%WXWIN% -Dicu_path=%ICUWIN% builddir
  - cmd: ninja -C builddir

