image: Visual Studio 2019

environment:
  ICUWIN: '%APPVEYOR_BUILD_FOLDER%\icu'

install:
  # Set paths to dependencies (based on architecture)
  - cmd: set PYTHON_ROOT=C:\python37-x64
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Set up the build environment
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_73_0
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64'
  # Install meson and ninja
  - cmd: pip install meson
  - cmd: chdir %APPVEYOR_BUILD_FOLDER%
  - cmd: curl -LO https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip
  - cmd: unzip ninja-win.zip
  # Download ICU
  - cmd: mkdir %ICUWIN%
  - cmd: chdir %ICUWIN%
  - cmd: curl -L -o icu.zip https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-Win64-MSVC2017.zip
  - cmd: 7z x icu.zip
  - cmd: chdir %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmd: meson --backend=ninja --buildtype release -Dicu_path=%ICUWIN% builddir
  - cmd: ninja -C builddir

