script_name="Editor Tampan (seleksi)"
script_description="Membantu membetulkan kata-kata yang sering salah penulisannya dalam subtitle/takarir supaya lebih tampan."
script_author="Max FireHeart"
script_version="1.1"

function tampan(subs, sel)
    for x, i in ipairs(sel) do
        line=subs[i]
        text=line.text
-- Elipsis
		:gsub("^\"","{Perlu elipsis?}\"")
		:gsub("  ([%s]?)"," ")
		:gsub("([a-z,]?)%.%.%.","%1 %.%.%.")
		:gsub("%.%.%.([a-z]?)","%.%.%. %1")
		:gsub("  "," ")
		:gsub("^({[^}]-})\"(%l)","%1%.%.%. \"%2")
		:gsub("(%a{[^}]-})$","%1 %.%.%.")
		:gsub("({[^}]-}),$","%1, %.%.%.")
		:gsub("%.%.%. %.%.%.%.%.%.","%.%.%.")
		:gsub("%.%.%. %.","%.%.%.%.")
		:gsub("^(%l)","%.%.%. %1")
		:gsub("^\"","%.%.%. \"")
		:gsub("([%a,])\"$","%1\" %.%.%.")
		:gsub("^({[^}]-})(%l)","%1 %.%.%. %2")		
		:gsub("(%l)$","%1 %.%.%.")
		:gsub(",$","%1 %.%.%.")	
		:gsub("%.%.%. %.%.%.","%.%.%.")
		:gsub("^ %.%.%. ","%.%.%. ")
		:gsub("}%.%.%. ","} %.%.%. ")
		:gsub("%.%.%.  %.%.%.","%.%.%.")
		:gsub("%.%.%. ,","%.%.%.,")
		:gsub("} , %.","}, %.")
		:gsub("\\N"," xxN")

-- Daftar kata yang sering salah dieja
		:gsub("Nampak","Tampak{(N)ampak}")
		:gsub(" nampak([%s%pkmnalt][uyna]?)"," tampak{nampak}%1")
		:gsub("Lagipula","Lagi pula{Lag(ipul)a}")
		:gsub("lagipula","lagi pula{lag(ipul)a}")
		:gsub(" anda([%s%p])"," Anda{(a)nda}%1")
		:gsub("Ajab([%s%pkmnalt][uyna]?)","Azab{Ajab}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ajab","%1azab{ajab}")
		:gsub("Ntah","Entah{(N)tah}")
		:gsub(" ntah([%s%pkmnalt][uyna]?)"," entah{ntah}%1")
		:gsub("Ok ","Oke{Oce} ")
		:gsub("Ok.","Oke.")
		:gsub("Ok,","Oke,")
		:gsub(" ok "," oke ")
		:gsub(" ok,"," oke,")
		:gsub(" ntah([%s%pkmnalt][uyna]?)"," entah{ntah}%1")
		:gsub("Nguap([%s%pkmnalt][uyna]?)","Menguap{Nguap}%1")
		:gsub(" nguap([%s%pkmnalt][uyna]?)"," menguap{nguap}%1")
		:gsub("Akte([%s%pkmnalt][uyna]?)","Akta{Akte}%1")
		:gsub("([%s%-mndpeka][egimrnu]?)akte","%1akta{akte}")
		:gsub("Aktip([%s%pkmnalt][uyna]?)","Aktif{Aktip}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)aktip","%1aktif{aktip}")	
		:gsub("([%s%-mndpekat][egimrnu]?)aktip","%1aktif{aktip}")							
		:gsub("Analisa([%s%pkmnalt][uyna]?)","Analisis{Analisa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)analisa","%1analisis{analisa}")
		:gsub("Apem([%s%pkmnalt][uyna]?)","Apam{Apem}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)apem","%1apam{apem}")
		:gsub("Aqidah([%s%pkmnalt][uyna]?)","Akidah{Aqidah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)aqidah","%1akidah{aqidah}")
		:gsub("Hadang([%s%pkmnalt][uyna]?)","Adang{Hadang}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hadang","%1adang{hadang}")
		:gsub("Handal([%s%pkmnalt][uyna]?)","Andal{Handal}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)handal","%1andal{handal}")
		:gsub("Al%-Qur\'an([%s%pkmnalt][uyna]?)","Alquran{Handal}%1")
		:gsub("Al%-Quran([%s%pkmnalt][uyna]?)","Alquran{Handal}%1")
		:gsub("Otomasi([%s%pkmnalt][uyna]?)","Automasi{Otomasi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)otomasi","%1automasi{otomasi}")
		:gsub("Otopsi([%s%pkmnalt][uyna]?)","Autopsi{Otopsi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)otopsi","%1autopsi{otopsi}")
		:gsub("Balsem([%s%pkmnalt][uyna]?)","Balsam{Balsem}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)balsem","%1balsam{balsem}")
		:gsub("Bandrol([%s%pkmnalt][uyna]?)","Banderol{Bandrol}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)bandrol","%1banderol{bandrol}")
		:gsub("Basoka([%s%pkmnalt][uyna]?)","Bazoka{Basoka}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)basoka","%1bazoka{basoka}")
		:gsub("Batalyon([%s%pkmnalt][uyna]?)","Batalion{Batalyon}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)batalyon","%1batalion{batalyon}")
		:gsub("Binari([%s%pkmnalt][uyna]?)","Biner{Binari}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)binari","%1biner{binari}")
		:gsub("Birahi([%s%pkmnalt][uyna]?)","Berahi{Birahi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)birahi","%1berahi{birahi}")
		:gsub("Bloon([%s%pkmnalt][uyna]?)","Beloon{Bloon}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)bloon","%1beloon{bloon}")
		:gsub("Brewok([%s%pkmnalt][uyna]?)","Berewok{Brewok}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)brewok","%1berewok{brewok}")
		:gsub("Catet([%s%pkmnalt][uyna]?)","Catat{Catet}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)catet","%1catat{catet}")
		:gsub("Cicak([%s%pkmnalt][uyna]?)","Cecak{Cicak}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cicak","%1cecak{cicak}")
		:gsub("Cidera([%s%pkmnalt][uyna]?)","Cedera{Cidera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cicak","%1cecak{cidera}")
		:gsub("Coklat","Cokelat{Co(kl)at}")
		:gsub("coklat","cokelat{co(kl)at}")
		:gsub("Clurit([%s%pkmnalt][uyna]?)","Celurit{Clurit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)clurit","%1celurit{clurit}")
		:gsub("Hembus([%s%pkmnalt][uyna]?)","Embus{Hembus}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hembus","%1embus{hembus}")
		:gsub("Gliserin([%s%pkmnalt][uyna]?)","Gliserol{Gliserin}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)gliserin","%1gliserol{gliserin}")
		:gsub("Goncang([%s%pkmnalt][uyna]?)","Guncang{Goncang}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)goncang","%1guncang{goncang}")
		:gsub("Greget([%s%pkmnalt][uyna]?)","Gereget{Greget}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)greget","%1gereget{greget}")
		:gsub("Hapal([%s%pkmnalt][uyna]?)","Hafal{Hapal}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hapal","%1hafal{hapal}")
		:gsub("Harafiah([%s%pkmnalt][uyna]?)","Harfiah{Harafiah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)harafiah","%1harfiah{harafiah}")
		:gsub("Himbau([%s%pkmnalt][uyna]?)","Imbau{Himbau}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)himbau","%1imbau{himbau}")
		:gsub("Hisap([%s%pkmnalt][uyna]?)","Isap{Hisap}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hisap","%1isap{hisap}")
		:gsub("Ihtiar([%s%pkmnalt][uyna]?)","Ikhtiar{Ihtiar}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ihtiar","%1ikhtiar{ihtiar}")
		:gsub("Indera([%s%pkmnalt][uyna]?)","Indra{Indera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)indera","%1indra{indera}")
		:gsub("Infantri([%s%pkmnalt][uyna]?)","Infantri{Infanteri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ifantri","%1infantri{infanteri}")
		:gsub("Misteri","Mist{}eri")
		:gsub("misteri","mist{}eri")
		:gsub("Isteri([%s%pkmnalt][uyna]?)","Istri{Isteri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)isteri","%1istri{isteri}")
		:gsub("Isolir([%s%pkmnalt][uyna]?)","Isolasi{Isolir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)isolir","%1isolasi{isolir}")
		:gsub("Cepit([%s%pkmnalt][uyna]?)","Jepit{Cepit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cepit","%1jepit{cepit}")
		:gsub("Kalo ","Kalau {Kalo( )}")
		:gsub("kalo ","kalau {kalo( )}")
		:gsub("Kadaluarsa([%s%pkmnalt][uyna]?)","Kedaluwarsa{Kadaluarsa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kadaluarsa","%1kedaluwarsa{kadaluarsa}")
		:gsub("Kadaluwarsa([%s%pkmnalt][uyna]?)","Kedaluwarsa{Kadaluwarsa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kadaluwarsa","%1kedaluwarsa{kadaluwarsa}")
		:gsub("Kangguru([%s%pkmnalt][uyna]?)","Kanguru{Kangguru}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kangguru","%1kanguru{kangguru}")
		:gsub("Kaos([%s%pkmnalt][uyna]?)","Kaus{Kaos}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kaos","%1kaus{kaos}")
		:gsub("Kwarsa([%s%pkmnalt][uyna]?)","Kuarsa{Kwarsa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kwarsa","%1kuarsa{kwarsa}")
		:gsub("Karir([%s%pkmnalt][uyna]?)","Karier{Karir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)karir","%1karier{karir}")
		:gsub("Kastil([%s%pkmnalt][uyna]?)","Kastel{Kastil}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kastil","%1kastel{kast(i)l}")
		:gsub("Kemilau([%s%pkmnalt][uyna]?)","Kilau{Kemilau}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kemilau","%1kilau{kemilau}")
		:gsub("Kendor([%s%pkmnalt][uyna]?)","Kendur{Kendor}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kendor","%1kendur{kendor}")
		:gsub("Kharisma([%s%pkmnalt][uyna]?)","Karisma{Kharisma}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kharisma","%1karisma{kharisma}")
		:gsub("Kokoh([%s%pkmnalt][uyna]?)","Kukuh{Kokoh}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kokoh","%1kukuh{kokoh}")
		:gsub("Komoditi([%s%pkmnalt][uyna]?)","Komoditas{Komoditi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)komoditi","%1komoditas{komoditi}")
		:gsub("Komplit([%s%pkmnalt][uyna]?)","Komplet{Komplit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)komplit","%1komplet{komplit}")
		:gsub("Koordinir([%s%pkmnalt][uyna]?)","Koordinasi{Koordinir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)koordinir","%1koordinasi{koordinir}")
		:gsub("Kopor([%s%pkmnalt][uyna]?)","Koper{Kopor}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kopor","%1koper{kopor}")
		:gsub("Kotbah([%s%pkmnalt][uyna]?)","Khotbah{kotbah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kotbah","%1khotbah{kotbah}")
		:gsub("Kutbah([%s%pkmnalt][uyna]?)","Khotbah{kotbah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kutbah","%1khotbah{kotbah}")
		:gsub("Kuatir([%s%pkmnalt][uyna]?)","Khawatir{kuatir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kuatir","%1khawatir{kuatir}")
		:gsub("Mengkilap([%s%pkmnalt][uyna]?)","Mengilap{Mengkilap}%1")
		:gsub("mengkilap([%s%pkmnalt][uyna]?)","mengilap{mengkilap}%1")
		:gsub("Mengkilat([%s%pkmnalt][uyna]?)","Mengilat{Mengkilat}%1")
		:gsub("mengkilat([%s%pkmnalt][uyna]?)","mengilat{mengkilat}%1")
		:gsub("Kumel([%s%pkmnalt][uyna]?)","Kumal{kumel}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kumel","%1kumal{kumel}")
		:gsub("Almari([%s%pkmnalt][uyna]?)","Lemari{Almari}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)almari","%1lemari{almari}")
		:gsub("Lansekap([%s%pkmnalt][uyna]?)","Lanskap{Lansekap}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)lansekap","%1lanskap{lansekap}")
		:gsub("Lapal([%s%pkmnalt][uyna]?)","Lafal{Lapal}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)lapal","%1lafal{lapal}")
		:gsub("Legalisir([%s%pkmnalt][uyna]?)","Legalisasi{Legalisir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)legalisir","%1legalisasi{legalisir}")
		:gsub("Lembab([%s%pkmnalt][uyna]?)","Lembap{Leembab}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)lembab","%1lembap{lembab}")
		:gsub("Lemes([%s%pkmnalt][uyna]?)","Lemas{Lemes}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)lemes","%1lemas{lemes}")
		:gsub("Amarah([%s%pkmnalt][uyna]?)","Amarah{sebenarnya \"Amarah\" enggak baku}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)amarah","%1amarah{sebenarnya \"amarah\" enggak baku}")
		:gsub("Makroni([%s%pkmnalt][uyna]?)","Makaroni{Makroni}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)makroni","%1makaroni{makroni}")
		:gsub("Mangkok([%s%pkmnalt][uyna]?)","Mangkuk{Mangkok}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mangkok","%1mangkuk{mangkok}")
		:gsub("Materai([%s%pkmnalt][uyna]?)","Meterai{Materai}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)materai","%1meterai{materai}")
		:gsub("Semakin([%s%pkmnalt][uyna]?)","Makin{Semakin}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)semakin","%1makin{semakin}")
		:gsub("Nafas([%s%pkmnalt][uyna]?)","Napas{Nafas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)nafas","%1napas{nafas}")
		:gsub("Nahkoda([%s%pkmnalt][uyna]?)","Nakhoda{Nahkoda}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)nahkoda","%1nakhoda{nahkoda}")
		:gsub("Napsu([%s%pkmnalt][uyna]?)","Nafsu{Napsu}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)napsu","%1nafsu{napsu}")
		:gsub("Nomer([%s%pkmnalt][uyna]?)","Nomor{Nomer}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)nomer","%1nomor{nomer}")
		:gsub("Narkotika([%s%pkmnalt][uyna]?)","Narkotik{Narkotika}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)narkotika","%1narkotik{narkotika}")
		:gsub("Orisinil([%s%pkmnalt][uyna]?)","Orisinal{Orisinil}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)orisinil","%1orisinal{orisinil}")
		:gsub("Original([%s%pkmnalt][uyna]?)","Orisinal{Original}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)original","%1orisinal{original}")
		:gsub("Omnivora([%s%pkmnalt][uyna]?)","Omnivor{Omnivora}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)omnivora","%1omnivor{omnivora}")
		:gsub("Herbivora([%s%pkmnalt][uyna]?)","Herbivor{Herbivora}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)herbivora","%1herbivor{herbivora}")
		:gsub("Karnivora([%s%pkmnalt][uyna]?)","Karnivor{Karnivora}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)karnivora","%1karnivor{karnivora}")
		:gsub("Insektivora([%s%pkmnalt][uyna]?)","Insektivor{Insektivora}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)insektivora","%1insektivor{insektivora}")
		:gsub("Personil([%s%pkmnalt][uyna]?)","Personel{Personil}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)personil","%1personel{personil}")
		:gsub("Piyama([%s%pkmnalt][uyna]?)","Piama{Piyama}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)piyama","%1piama{piyama}")
		:gsub("Plat([%s%pkmnalt][uyna]?)","Pelat{Plat}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)plat","%1pelat{plat}")
		:gsub("Politisi([%s%pkmnalt][uyna]?)","Politikus{Politisi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)politisi","%1politikus{politisi}")
		:gsub("Rame([%s%p])","Ramai{Ram(e)}%1")
		:gsub("([%s%p])rame([%s%p])","%1ramai{rame}%2")
		:gsub("Rejeki([%s%pkmnalt][uyna]?)","Rezeki{Rejeki}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)rejeki","%1rezeki{rejeki}")
		:gsub("Rejim([%s%pkmnalt][uyna]?)","Rezim{Rejim}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)rejim","%1rezim{rejim}")
		:gsub("Ritma([%s%pkmnalt][uyna]?)","Ritme{Ritma}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ritma","%1ritme{ritma}")
		:gsub("Ritmik([%s%pkmnalt][uyna]?)","Ritmis{Ritmik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ritmik","%1ritmis{ritmik}")
		:gsub("Rubuh([%s%pkmnalt][uyna]?)","Roboh{Rubuh}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)rubuh","%1roboh{rubuh}")
		:gsub("Samsara([%s%pkmnalt][uyna]?)","Sengsara{Samsara}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)samsara","%1sengsara{samsara}")
		:gsub("Samudera([%s%pkmnalt][uyna]?)","Samudra{Samudera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)samudera","%1samudra{samudera}")
		:gsub("Satir([%s%pkmnalt][uyna]?)","Satire{Satir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)satir","%1satire{satir}")
		:gsub("Semberani([%s%pkmnalt][uyna]?)","Sembrani{Semberani}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)semberani","%1sembrani{semberani}")
		:gsub("Semberono([%s%pkmnalt][uyna]?)","Sembrono{Semberono}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)semberono","%1sembrono{semberono}")
		:gsub("Sepanduk([%s%pkmnalt][uyna]?)","Spanduk{Sepanduk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sepanduk","%1spanduk{sepanduk}")
		:gsub("Supir([%s%pkmnalt][uyna]?)","Sopir{Supir}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)supir","%1sopir{supir}")
		:gsub("nyupir([%s%pkmnalt][uyna]?)","nyopir{nyupir}%1")
		:gsub("Stop([%s%pkmnalt][uyna]?)","Setop{Stop}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)stop%pkmnal][uyna]?)","%1setop{stop}")
		:gsub("Setasiun([%s%pkmnalt][uyna]?)","Stasiun{Setasiun}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)setasiun","%1stasiun{setasiun}")
		:gsub("Silahkan([%s%pkmnalt][uyna]?)","Silakan{Silahkan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)silahkan","%1silakan{silahkan}")
		:gsub("Sebrang([%s%pkmnalt][uyna]?)","Seberang{Sebrang}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sebrang","%1seberang{sebrang}")
		:gsub("([%s%-mndpekat][egimrnu]?)nyebrang","%1nyeberang{nyebrang}")
		:gsub("Seterika([%s%pkmnalt][uyna]?)","Strika{Seterika}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)seterika","%1strika{seterika}")
		:gsub("([%s%-mndpekat][egimrnu]?)nyeterika","%1nyetrika{nyeterika}")
		:gsub("Tangker([%s%pkmnalt][uyna]?)","Tanker{Tangker}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tangker","%1tanker{tangker}")
		:gsub("Tarip([%s%pkmnalt][uyna]?)","Tarif{Tarip}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tarip","%1tarif{tarip}")
		:gsub("Telor([%s%pkmnalt][uyna]?)","Telur{Telor}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)telor","%1telur{telor}")
		:gsub("Tauge([%s%pkmnalt][uyna]?)","Taoge{Tauge}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tauge","%1taoge{tauge}")
		:gsub("Tipes([%s%pkmnalt][uyna]?)","Tifus{Tipes}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tipus","%1tifus{tipes}")
		:gsub("Trampil([%s%pkmnalt][uyna]?)","Terampil{Trampil}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)trampil","%1terampil{trampil}")
		:gsub("Hutang([%s%pkmnalt][uyna]?)","Utang{Hutang}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hutang","%1utang{hutang}")
		:gsub("Jaman([%s%pkmnalt][uyna]?)","Zaman{Jaman}%1")
		:gsub("( jaman"," zaman{(jaman}")
		:gsub("Jamrud([%s%pkmnalt][uyna]?)","Zamrud{Jamrud}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jamrud","%1zamrud{jamrud}")
		:gsub("Jiarah([%s%pkmnalt][uyna]?)","Ziarah{Jiarah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jiarah","%1ziarah{jiarah}")
		:gsub("Zinah([%s%pkmnalt][uyna]?)","Zina{Zinah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)zinah","%1zina{zinah}")

		:gsub("Apek([%s%pkmnalt][uyna]?)","Apak{Apek}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)apek","%1apak{apek}")
		:gsub("Cemilan([%s%pkmnalt][uyna]?)","Camilan{Cemilan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cemilan","%1camilan{cemilan}")
		:gsub("Frase([%s%pkmnalt][uyna]?)","Frasa{Frase}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)frase","%1frasa{frase}")
		:gsub("Ketapel([%s%pkmnalt][uyna]?)","Katapel{Ketapel}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ketapel","%1katapel{ketapel}")
		:gsub("Menejer([%s%pkmnalt][uyna]?)","Manajer{Menejer}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)menejer","%1manajer{menejer}")
		:gsub("Seksama([%s%pkmnalt][uyna]?)","Saksama{Seksama}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)seksama","%1saksama{seksama}")
		:gsub("Senggama([%s%pkmnalt][uyna]?)","Sanggama{Senggama}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)senggama","%1sanggama{senggama}")
		:gsub("Sekedar([%s%pkmnalt][uyna]?)","Sekadar{Sekedar}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sekedar","%1sekadar{sekedar}")
		:gsub("Seprei([%s%pkmnalt][uyna]?)","Seprai{Seprei}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)seprei","%1seprai{seprei}")
		:gsub("Semedi([%s%pkmnalt][uyna]?)","Semadi{Semedi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)semedi","%1semadi{semedi}")

		:gsub("Amandemen([%s%pkmnalt][uyna]?)","Amendemen{Amandemen}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)amandemen","%1amendemen{amandemen}")
		:gsub("Algoritma([%s%pkmnalt][uyna]?)","Algoritme{Algoritma}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)algoritma","%1algoritme{algoritma}")
		:gsub("Aritmatika([%s%pkmnalt][uyna]?)","Aritmetika{Aritmatika}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)aritmatika","%1aritmetika{aritmatika}")
		:gsub("Sekular([%s%pkmnalt][uyna]?)","Sekuler{Sekular}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sekular","%1sekuler{sekuler}")
		:gsub("Selular([%s%pkmnalt][uyna]?)","Seluler{Selular}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)selular","%1seluler{seluler}")
		:gsub("Selular([%s%pkmnalt][uyna]?)","Seluler{Selular}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)selular","%1seluler{seluler}")
		:gsub("Sirkular([%s%pkmnalt][uyna]?)","Sirkuler{Selular}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sirkular","%1sirkuler{sirkuler}")

		:gsub("Afdol([%s%pkmnalt][uyna]?)","Afdal{Afdol}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)afdol","%1afdal{afdol}")
		:gsub("Antri([%s%pkmnalt][uyna]?)","Antre{Antri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)antri","%1antre{antri}")
		:gsub("Apotik([%s%pkmnalt][uyna]?)","Apotek{Atlit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)apotik","%1apotek{apotik}")
		:gsub("Atlit([%s%pkmnalt][uyna]?)","Atlet{Atlit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)atlit","%1atlet{atlit}")
		:gsub("Cidera([%s%pkmnalt][uyna]?)","Cedera{Cidera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cidera","%1cedera{cidera}")
		:gsub("Cendikiawan([%s%pkmnalt][uyna]?)","Cendekiawan{Cendikiawan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cendikiawan","%1cendekiawan{cendikiawan}")
		:gsub("Cinderamata([%s%pkmnalt][uyna]?)","Cenderamata{Cinderamata}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cinderamata","%1cenderamata{cinderamata}")
		:gsub("Debet([%s%pkmnalt][uyna]?)","Debit{Debet}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)debet","%1debit{debet}")
		:gsub("Dekrit([%s%pkmnalt][uyna]?)","Dekret{Dekrit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)dekrit","%1dekret{dekrit}")
		:gsub("Diskotik([%s%pkmnalt][uyna]?)","Diskotek{Diskotik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)diskotik","%1diskotek{diskotik}")
		:gsub("Ekstrim([%s%pkmnalt][uyna]?)","Ekstrem{Ekstrim}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ekstrim","%1ekstrem{ekstrim}")
		:gsub("Konkrit([%s%pkmnalt][uyna]?)","Konkret{Konkrit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)konkrit","%1konkret{konkrit}")
		:gsub("Musium([%s%pkmnalt][uyna]?)","Museum{Musium}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)musium","%1museum{musium}")
		:gsub("Pinalti([%s%pkmnalt][uyna]?)","Penalti{Pinalti}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)pinalti","%1penalti{pinalti}")
		:gsub("Piranti([%s%pkmnalt][uyna]?)","Peranti{Piranti}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)piranti","%1peranti{piranti}")
		:gsub("Sistim([%s%pkmnalt][uyna]?)","Sistem{Sistim}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sistim","%1sistem{sistim}")
		:gsub("Teoritis([%s%pkmnalt][uyna]?)","Teoretis{Teoritis}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sistim","%1sistem{sistim}")

		:gsub("Cengkeh([%s%pkmnalt][uyna]?)","Cengkih{Cengkeh}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cengkeh","%1cengkih{cengkeh}")
		:gsub("Hakekat([%s%pkmnalt][uyna]?)","Hakikat{Hakekat}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hakekat","%1hakikat{hakekat}")
		:gsub("Kempes([%s%pkmnalt][uyna]?)","Kempis{Kempes}%1")
		:gsub("Mengempes([%s%pkmnalt][uyna]?)","Mengempis{Mengempes}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mengempes","%1mengempis{mengempes}")
		:gsub("([%s%-mndpekat][egimrnu]?)kempes","%1kempis{kempes}")
		:gsub("Ledeng([%s%pkmnalt][uyna]?)","Leding{Ledeng}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ledeng","%1leding{ledeng}")
		:gsub("Nasehat([%s%pkmnalt][uyna]?)","Nasihat{Nasehat}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)nasehat","%1nasihat{nasehat}")
		:gsub("Praktik([%s%pkmnalt][uyna]?)","Praktek{Praktik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)praktik","%1praktek{praktik}")
		:gsub("Resiko([%s%pkmnalt][uyna]?)","Risiko{Resiko}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)resiko","%1risiko{resiko}")
		:gsub("Resleting([%s%pkmnalt][uyna]?)","Ritsleting{Resleting}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)resleting","%1ritsleting{resleting}")

		:gsub("Amuba([%s%pkmnalt][uyna]?)","Ameba{Amuba}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)amuba","%1ameba{amuba}")
		:gsub("Sorban([%s%pkmnalt][uyna]?)","Serban{Sorban}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sorban","%1serban{sorban}")
		:gsub("Sorban([%s%pkmnalt][uyna]?)","Serban{Sorban}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sorban","%1serban{sorban}")
		:gsub("Pastur([%s%pkmnalt][uyna]?)","Pastor{Pastur}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)pastur","%1pastor{pastur}")
		:gsub("Lobang([%s%pkmnalt][uyna]?)","Lubang{Lobang}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)lobang","%1lubang{lobang}")
		:gsub("Konsekwensi([%s%pkmnalt][uyna]?)","Konsekuensi{Konsekwensi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)konsekwensi","%1konsekuensi{konsekwensi}")
		:gsub("Kwintal([%s%pkmnalt][uyna]?)","Kuintal{Kwintal}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kwintal","%1kuintal{kwintal}")
		:gsub("Jadual([%s%pkmnalt][uyna]?)","Jadwal{Jadual}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jadual","%1jadwal{jadual}")
		:gsub("Subyektif([%s%pkmnalt][uyna]?)","Subjektif{Subyektif}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)subyektif","%1subjektif{subyektif}")
		:gsub("Obyektif([%s%pkmnalt][uyna]?)","Objektif{Obyektif}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)obyektif","%1objektif{obyektif}")
		:gsub("Faham([%s%pkmnalt][uyna]?)","Paham{Faham}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)faham","%1paham{faham}")
		:gsub("Propinsi([%s%pkmnalt][uyna]?)","Provinsi{Propinsi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)propinsi","%1provinsi{propinsi}")
		:gsub("Jerembab([%s%pkmnalt][uyna]?)","Jerembap{Jerembab}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jerembab","%1jerembap{jerembab}")
		:gsub("Babtis([%s%pkmnalt][uyna]?)","Baptis{Babtis}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)babtis","%1baptis{babtis}")
		:gsub("Tekat([%s%pkmnalt][uyna]?)","Tekad{Tekat}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tekat","%1tekad{tekat}")
		:gsub("Limosin([%s%pkmnalt][uyna]?)","Limusin{Limosin}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)limosin","%1limusin{limosin}")
		:gsub("Bejad([%s%pkmnalt][uyna]?)","Bejat{Bejad}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)bejad","%1bejat{bejad}")
		:gsub("Nekad([%s%pkmnalt][uyna]?)","Nekat{Nekad}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)nekad","%1nekat{nekad}")
		:gsub("Skuad([%s%pkmnalt][uyna]?)","Skuat{Skuad}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)skuad","%1skuat{skuad}")
		:gsub("Marjin([%s%pkmnalt][uyna]?)","Margin{Marjin}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)marjin","%1margin{marjin}")
		:gsub("Projek([%s%pkmnalt][uyna]?)","Proyek{Projek}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)projek","%1proyek{projek}")
		:gsub("Azas([%s%pkmnalt][uyna]?)","Asas{Azas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)azas","%1asas{azas}")
		:gsub("Jenasah([%s%pkmnalt][uyna]?)","Jenazah{Jenasah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jenasah","%1jenazah{jenasah}")
		:gsub("Bathin([%s%pkmnalt][uyna]?)","Batin{Bathin}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)bathin","%1batin{bathin}")
		:gsub("Katholik([%s%pkmnalt][uyna]?)","Katolik{Katholik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)katholik","%1katolik{katholik}")
		:gsub("Theologi([%s%pkmnalt][uyna]?)","Teologi{Theologi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)theologi","%1teologi{theologi}")

		:gsub("Anugrah([%s%pkmnalt][uyna]?)","Anugerah{Anugrah}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)anugrah","%1anugerah{anugrah}")
		:gsub("Cendrawasih([%s%pkmnalt][uyna]?)","Cenderawasih{Cendrawasih}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)cendrawasih","%1cenderawasih{cendrawasih}")
		:gsub("Jendral([%s%pkmnalt][uyna]?)","Jenderal{Jendral}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)jendral","%1jenderal{jendral}")
		:gsub("Kripik([%s%pkmnalt][uyna]?)","Keripik{Kripik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kripik","%1keripik{kripik}")
		:gsub("Krupuk([%s%pkmnalt][uyna]?)","Kerupuk{Krupuk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)krupuk","%1kerupuk{krupuk}")
		:gsub("Ksatria([%s%pkmnalt][uyna]?)","Kesatria{Ksatria}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ksatria","%1kesatria{ksatria}")
		:gsub("Satria([%s%pkmnalt][uyna]?)","Kesatria{Satria}%1")
		:gsub(" satria"," kesatria{(s)atria}")
		:gsub("Mentri([%s%pkmnalt][uyna]?)","Menteri{Mentri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mentri","%1menteri{mentri}")
		:gsub("Negri([%s%pkmnalt][uyna]?)","Negeri{Negri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)negri","%1negeri{negri}")
		:gsub("Prancis([%s%pkmnalt][uyna]?)","Perancis{Prancis}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)prancis","%1perancis{prancis}")
		:gsub("Sumatra([%s%pkmnalt][uyna]?)","Sumatera{Sumatra}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sumatra","%1sumatera{sumatra}")
		:gsub("Justeru([%s%pkmnalt][uyna]?)","Justru{Justeru}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)justeru","%1justru{justeru}")
		:gsub("Perajurit([%s%pkmnalt][uyna]?)","Prajurit{Perajurit}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)perajurit","%1prajurit{perajurit}")
		:gsub("Putera([%s%pkmnalt][uyna]?)","Putra{Putera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)putera","%1putra{putera}")
		:gsub("Puteri([%s%pkmnalt][uyna]?)","Putri{Puteri}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)puteri","%1putri{puteri}")
		:gsub("Sastera([%s%pkmnalt][uyna]?)","Sastra{Sastera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sastera","%1sastra{sastera}")
		:gsub("Sutera([%s%pkmnalt][uyna]?)","Sutra{Sutera}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sutera","%1sutra{sutera}")
		:gsub("Terompet([%s%pkmnalt][uyna]?)","Trompet{Terompet}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)terompet","%1trompet{terompet}")
		:gsub("Iklas([%s%pkmnalt][uyna]?)","Ikhlas{Iklas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)iklas","%1ikhlas{iklas}")
		:gsub("Kusyuk([%s%pkmnalt][uyna]?)","Khusyuk{Kusyuk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kusyuk","%1khusyuk{kusyuk}")
		:gsub("Makluk([%s%pkmnalt][uyna]?)","Makhluk{Makluk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)makluk","%1makhluk{makluk}")
		:gsub("Mahluk([%s%pkmnalt][uyna]?)","Makhluk{Mahluk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mahluk","%1makhluk{mahluk}")
		:gsub("Mahkluk([%s%pkmnalt][uyna]?)","Makhluk{Mahkluk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mahkluk","%1makhluk{mahkluk}")
		:gsub("Tahayul([%s%pkmnalt][uyna]?)","Takhayul{Tahayul}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tahayul","%1takhayul{tahayul}")
		:gsub("Tahta([%s%pkmnalt][uyna]?)","Takhta{Tahta}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tahta","%1takhta{tahta}")
		:gsub("Tehnik([%s%pkmnalt][uyna]?)","Teknik{Tehnik}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)tehnik","%1teknik{tehnik}")
		:gsub("Sex([%s%pkmnalt][uyna]?)","Seks{Sex}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sex","%1seks{sex}")
		:gsub("Taxi([%s%pkmnalt][uyna]?)","Taksi{Taxi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)taxi","%1taksi{taxi}")
		:gsub("Insyaf([%s%pkmnalt][uyna]?)","Insaf{Insyaf}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)insyaf","%1insaf{insyaf}")
		:gsub("Syaraf([%s%pkmnalt][uyna]?)","Saraf{Syaraf}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)syaraf","%1saraf{syaraf}")
		:gsub("Mahsyur([%s%pkmnalt][uyna]?)","Masyhur{Mahsyur}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mahsyur","%1masyhur{mahsyur}")

		:gsub("Diagnosa([%s%pkmnalt][uyna]?)","Diagnosis{Diagnosa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)diagnosa","%1diagnosis{diagnosa}")
		:gsub("Aktifitas([%s%pkmnalt][uyna]?)","Aktivitas{Aktifitas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)aktifitas","%1aktivitas{aktifitas}")
		:gsub("Efektifitas([%s%pkmnalt][uyna]?)","Efektifitas{Efektifitas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)efektifitas","%1efektivitas{efektifitas}")
		:gsub("Produktifitas([%s%pkmnalt][uyna]?)","Produktivitas{Produktifitas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)produktifitas","%1produktivitas{produktifitas}")
		:gsub("Sportifitas([%s%pkmnalt][uyna]?)","Sportivitas{Sportifitas}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sportifitas","%1sportivitas{sportifitas}")
		:gsub("Komoditi([%s%pkmnalt][uyna]?)","Komoditas{Komoditi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)komoditi","%1komoditas{komoditi}")
		:gsub("Komuniti([%s%pkmnalt][uyna]?)","Komunitas{Komuniti}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)komuniti","%1komunitas{komuniti}")
		:gsub("Realita([%s%p])","Realitas{Realita}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)realiti([%s%p])","%1realitas{realita}")
		:gsub("Realiti([%s%pkmnalt][uyna]?)","Realitas{Realiti}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)realiti","%1realitas{realiti}")
		:gsub("Selebriti([%s%pkmnalt][uyna]?)","Selebritas{Selebriti}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)selebriti","%1selebritas{selebriti}")
		:gsub("Moderen([%s%pkmnalt][uyna]?)","Modern{Moderen}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)moderen","%1modern{moderen}")
		:gsub("Pasport([%s%pkmnalt][uyna]?)","Paspor{Pasport}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)pasport","%1paspor{pasport}")
		:gsub("Perduli([%s%pkmnalt][uyna]?)","Peduli{Perduli}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)perduli","%1peduli{perduli}")
		:gsub("Ramadhan([%s%pkmnalt][uyna]?)","Ramadan{Ramadhan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)ramadhan","%1ramadan{ramadhan}")
		:gsub("Rapih([%s%pkmnalt][uyna]?)","Rapi{Rap(ih)}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)rapih","%1rapi{rap(ih)}")
		:gsub("Standard([%s%pkmnalt][uyna]?)","Standar{Standard}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)standardisasi","%1standarisasi{standardisasi}")

		:gsub("Pungkir([%s%pkmnalt][uyna]?)","Mungkir{Pungkir}%1")
		:gsub("([%s%pkmnalt][egimrnu]?)pungkir","%1mungkir{pungkir}")
		:gsub("China([%s%pkmnalt][uyna]?)","Cina{China}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)china","%1cina{china}")
		:gsub("Hisap([%s%pkmnalt][uyna]?)","Isap{Hisap}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)hisap","%1isap{hisap}")
		:gsub("Maghrib([%s%pkmnalt][uyna]?)","Magrib{Maghrib}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)maghrib","%1magrib{maghrib}")
		:gsub("Do\'a([%s%pkmnalt][uyna]?)","Doa{Do\'a}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)do\'a","%1doa{do\'a}")
		:gsub("Asik([%s%p])","Asyik{Asik}%1")
		:gsub(" asik"," asyik{asik}")
		:gsub("([%s%-mndpekat][egimrnu]?)mengasikan","%1mengasyikkan{mengasikan}")
		:gsub("Mengasikan([%s%pkmnalt][uyna]?)","Mengasyikkan{Mengasikan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mengasikan","%1mengasyikkan{mengasikan}")
		:gsub("Mengasyikan([%s%pkmnalt][uyna]?)","Mengasyikkan{Mengasyikan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mengasyikan","%1mengasyikkan{mengasyikan}")
		:gsub("Mengasikkan([%s%pkmnalt][uyna]?)","Mengasyikkan{Mengasikkan}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mengasikkan","%1mengasyikkan{mengasikkan}")
		:gsub("([%s%-mndpekat][egimrnu]?)do\'a","%1doa{do\'a}")
		:gsub("Mujizat([%s%pkmnalt][uyna]?)","Mukjizat{Mujizat}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)mujizat","%1mukjizat{mujizat}")
		:gsub("Ambulan([%s%p])","Ambulans{Ambulan}%1")
		:gsub("ambulan([%s%p])","ambulans{ambulan}%1")
		:gsub("Ensiklopedi([%s%p])","Ensiklopedia{Ensiklopedi}%1")
		:gsub("ensiklopedi([%s%p])","ensiklopedia{ensiklopedi}%1")
		:gsub("Elit([%s%p])","Elite{Elit}%1")
		:gsub("elit([%s%p])","elite{elit}%1")
		:gsub("Gladi([%s%p])","Geladi{Gladi}%1")
		:gsub("gladi([%s%p])","geladi{gladi}%1")
		:gsub("Itali([%s%p])","Italia{Itali}%1")
		:gsub("Klenteng([%s%p])","Kelenteng{Klenteng}%1")
		:gsub("klenteng([%s%p])","kelenteng{klenteng}%1")
		:gsub("Kontruksi([%s%p])","Konstruksi{Kontruksi}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kontruksi","%1konstruksi{kontruksi}")
		:gsub("Masal([%s%p])","Massal{Masal}%1")
		:gsub("masal([%s%p])","massal{masal}%1")
		:gsub("Merk([%s%pkmnalt][uyna]?)","Merek{Merk}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)merk","%1merek{merk}")
		:gsub("Respon([%s%pkmnalt][uyna]?)","Respons{Respon}%1")
		:gsub("respon([%s%pkmnalt][uyna]?)","respons{respon}%1")
		:gsub("Skak([%s%p])","Sekak{Skak}%1")
		:gsub("skak([%s%p])","sekak{skak}%1")
		:gsub("Stir([%s%p])","Setir{Stir}%1")
		:gsub("stir([%s%p])","setir{stir}%1")
		:gsub("Singapur([%s%p])","Singapura{Singapur}%1")
		:gsub("Amphibi([%s%p])","Amfibi{Amphibi}%1")
		:gsub("amphibi([%s%p])","amfibi{amphibi}%1")
		:gsub("Anjlog([%s%p])","Anjlok{Anjlog}%1")
		:gsub("anjlog([%s%p])","anjlok{anjlog}%1")
		:gsub("Alpukat([%s%p])","Avokad{Alpukat}%1")
		:gsub("alpukat([%s%p])","avokad{alpukat}%1")
		:gsub("Bolpen([%s%p])","Pulpen{Bolpen}%1")
		:gsub("bolpen([%s%p])","pulpen{bolpen}%1")
		:gsub("Cabe([%s%p])","Cabai{Cabe}%1")
		:gsub("cabe([%s%p])","cabai{cabe}%1")
		:gsub("Ceret([%s%p])","Cerek{Ceret}%1")
		:gsub("ceret([%s%p])","cerek{ceret}%1")
		:gsub("Differen([%s%pkmnalt][uyna]?)","Diferen{Differen}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)differen","%1diferen{differen}")
		:gsub("Duren([%s%p])","Durian{Duren}%1")
		:gsub("duren([%s%p])","durian{duren}%1")
		:gsub("Faksimil([%s%p])","Faksimile{Faksimil}%1")
		:gsub("faksimil[%s%p]}","faksimile{faksimil}%1")
		:gsub("Faksimili([%s%p])","Faksimile{Faksimili}%1")
		:gsub("faksimili([%s%p])","faksimile{faksimili}%1")
		:gsub("Graha([%s%p])","Gerha{Graha}%1")
		:gsub("graha([%s%p])","gerha{graha}%1")
		:gsub("Goblog([%s%p])","Goblok{Goblog}%1")
		:gsub("goblog([%s%p])","goblok{goblog}%1")
		:gsub("Gubug([%s%p])","Gubuk{Gubug}%1")
		:gsub("gubug([%s%p])","gubuk{gubug}%1")
		:gsub("Imaginasi([%s%p])","Imajinasi{Imaginasi}%1")
		:gsub("imaginasi([%s%p])","imajinasi{imaginasi}%1")
		:gsub("Jerigen([%s%p])","Jeriken{Jerigen}%1")
		:gsub("jerigen([%s%p])","jeriken{jerigen}%1")
		:gsub("Jirigen([%s%p])","Jeriken{Jirigen}%1")
		:gsub("jirigen([%s%p])","jeriken{jirigen}%1")
		:gsub("Carut-marut([%s%p])","Karut-marut{Carut-marut}%1")
		:gsub("carut-marut([%s%p])","karut-marut{carut-marut}%1")
		:gsub("Mahzab([%s%p])","Mazhab{Mahzab}%1")
		:gsub("mahzab([%s%p])","mazhab{mahzab}%1")
		:gsub("Milyar([%s%pkmnalt][uyna]?)","Miliar{Milyar}%1")
		:gsub("milyar([%s%pkmnalt][uyna]?)","miliar{milyar}%1")
		:gsub("Mulya([%s%p])","Mulia{Mulya}%1")
		:gsub("mulya([%s%p])","mulia{mulya}%1")
		:gsub("Negoisasi([%s%p])","Negosiasi{Negoisasi}%1")
		:gsub("negoisasi([%s%p])","negosiasi{negoisasi}%1")
		:gsub("Automotif([%s%p])","Otomotifi{Automotif}%1")
		:gsub("automotif([%s%p])","otomotif{automotif}%1")
		:gsub("Pararel([%s%pkmnalt][uyna]?)","Paralel{Pararel}%1")
		:gsub("pararel([%s%pkmnalt][uyna]?)","paralel{pararel}%1")
		:gsub("Paska([%s%p])","Pasca{Paska}%1")
		:gsub("paska([%s%p])","pasca{paska}%1")
		:gsub("Prosen([%s%pkmnalt][uyna]?)","Persen{Prosen}%1")
		:gsub("prosen([%s%pkmnalt][uyna]?)","prosen{prosen}%1")
		:gsub("Prosentase([%s%p])","Persentase{Prosentase}%1")
		:gsub("prosentase([%s%p])","persentase{prosentase}%1")
		:gsub("Proff([%s%p])","Prof{Proff}%1")
		:gsub("proff([%s%p])","prof{proff}%1")
		:gsub("Proffesor([%s%p])","Profesor{Proffesor}%1")
		:gsub("proffesor([%s%p])","profesor{proffesor}%1")
		:gsub("Rapot([%s%p])","Rapor{Rapot}%1")
		:gsub("rapot([%s%p])","rapor{rapot}%1")
		:gsub("Rileks([%s%p])","Relaks{Rileks}%1")
		:gsub("rileks([%s%p])","relaks{rileks}%1")
		:gsub("Rileksasi([%s%p])","Relaksasi{Rileksasi}%1")
		:gsub("rileksasi([%s%p])","relaksasi{rileksasi}%1")
		:gsub("Sekertaris([%s%p])","Sekretaris{Sekertaris}%1")
		:gsub("sekertaris([%s%p])","sekretaris{sekertaris}%1")
		:gsub("Sensorik([%s%p])","Sensoris{Sensorik}%1")
		:gsub("sensorik([%s%p])","sensoris{sensorik}%1")
		:gsub("Sentausa([%s%p])","Sentosa{Sentausa}%1")
		:gsub("sentausa([%s%p])","sentosa{sentausa}%1")
		:gsub("Formil([%s%p])","Formal{Formil}%1")
		:gsub("formil([%s%p])","formal{formil}%1")
		:gsub("Taqwa([%s%p])","Takwa{Taqwa}%1")
		:gsub("taqwa([%s%p])","takwa{taqwa}%1")
		:gsub("Tauco([%s%p])","Taoco{Tauco}%1")
		:gsub("tauco([%s%p])","taoco{tauco}%1")
		:gsub("Tauladan([%s%p])","Teladan{Tauladan}%1")
		:gsub("tauladan([%s%p])","teladan{tauladan}%1")
		:gsub("Hirarki([%s%p])","Hierarki{Hirarki}%1")
		:gsub("hirarki([%s%p])","hierarki{hirarki}%1")
		:gsub("Taubat([%s%pkmnalt][uyna]?)","Tobat{Taubat}%1")
		:gsub("taubat([%s%pkmnalt][uyna]?)","tobat{taubat}%1")
		:gsub("Trilyun([%s%pkmnalt][uyna]?)","Triliun{Trilyun}%1")
		:gsub("trilyun([%s%pkmnalt][uyna]?)","triliun{trilyun}%1")
		:gsub("Hipotesa([%s%pkmnalt][uyna]?)","Hipotesis{Hipotesa}%1")
		:gsub("hipotesa([%s%pkmnalt][uyna]?)","hipotesis{hipotesa}%1")
		:gsub("Strawberi([%s%pkmnalt][uyna]?)","Stroberi{Strawberi}%1")
		:gsub("strawberi([%s%pkmnalt][uyna]?)","stroberi{strawberi}%1")
		:gsub("Strawbery([%s%pkmnalt][uyna]?)","Stroberi{Strawbery}%1")
		:gsub("strawbery([%s%pkmnalt][uyna]?)","stroberi{strawbery}%1")
		:gsub("Strawberry([%s%pkmnalt][uyna]?)","Strawberry{di kamus -> Stroberi}%1")
		:gsub("strawberry([%s%pkmnalt][uyna]?)","strawberry{di kamus -> stroberi}%1")
		:gsub("Arbei([%s%p])","Stroberi{Arbei}%1")
		:gsub("arbei([%s%pkmnalt][uyna]?)","stroberi{arbei}%1")
		:gsub("Dekrit([%s%p])","Dekret{Dekrit}%1")
		:gsub("dekrit([%s%pkmnalt][uyna]?)","dekret{dekrit}%1")
		:gsub("Detil([%s%pkmnalt][uyna]?)","Detail{Detil}%1")
		:gsub("detil([%s%pkmnalt][uyna]?)","detail{detil}%1")
		:gsub("Pondasi([%s%pkmnalt][uyna]?)","Fondasi{Pondasi}%1")
		:gsub("pondasi([%s%pkmnalt][uyna]?)","fondasi{pondasi}%1")
		:gsub("Fikir([%s%pkmnalt][uyna]?)","Pikir{Fikir}%1")
		:gsub("fikir([%s%pkmnalt][uyna]?)","pikir{fikir}%1")
		:gsub("Sepedah","Sepeda{Sepeda(h)}")
		:gsub("sepedah","sepeda{sepeda(h)}")
		:gsub("Familiar","Familier{Famili(a)r}")
		:gsub("familiar","familier{famili(a)r}")

		:gsub("([cws]h?)ould not","%1ouldn't")

-- Imbuhan
		:gsub("Terlanjur([%s%pkmnalt][uyna]?)","Telanjur{Terlanjur}%1")
		:gsub("terlanjur([%s%pkmnalt][uyna]?)","telanjur{terlanjur}%1")
		:gsub("Terlentang([%s%pkmnalt][uyna]?)","Telentang{Terlentang}%1")
		:gsub("terlentang([%s%pkmnalt][uyna]?)","telentang{terlentang}%1")
		:gsub("Terlantar([%s%pkmnalt][uyna]?)","Telantar{Terlantar}%1")
		:gsub("terlantar([%s%pkmnalt][uyna]?)","telantar{terlantar}%1")
		:gsub("Terbersih([%s%pkmnalt][uyna]?)","Tebersih{Terbersih}%1")
		:gsub("terbersih([%s%pkmnalt][uyna]?)","tebersih{terbersih}%1")
		:gsub("Terbersit([%s%pkmnalt][uyna]?)","Tebersit{Terbersit}%1")
		:gsub("terbersit([%s%pkmnalt][uyna]?)","tebersit{terbersit}%1")
		:gsub("Terpercaya([%s%pkmnalt][uyna]?)","Tepercaya{Terpercaya}%1")
		:gsub("terpercaya([%s%pkmnalt][uyna]?)","tepercaya{terpercaya}%1")
		:gsub("Terperdaya([%s%pkmnalt][uyna]?)","Teperdaya{Terperdaya}%1")
		:gsub("terperdaya([%s%pkmnalt][uyna]?)","teperdaya{terperdaya}%1")
		:gsub("Terpercik([%s%pkmnalt][uyna]?)","Tepercik{Terpercik}%1")
		:gsub("terpercik([%s%pkmnalt][uyna]?)","tepercik{terpercik}%1")
		:gsub("Terpergok([%s%pkmnalt][uyna]?)","Tepergok{Terpergok}%1")
		:gsub("terpergok([%s%pkmnalt][uyna]?)","tepergok{terpergok}%1")
		:gsub("Tercermin([%s%pkmnalt][uyna]?)","Tecermin{Tercermin}%1")
		:gsub("tercermin([%s%pkmnalt][uyna]?)","tecermin{tercermin}%1")
		:gsub("Berternak([%s%pkmnalt][uyna]?)","Beternak{Berternak}%1")
		:gsub("berternak([%s%pkmnalt][uyna]?)","beternak{berternak}%1")
		:gsub("Berpergian([%s%pkmnalt][uyna]?)","Bepergian{Berpergian}%1")
		:gsub("berpergian([%s%pkmnalt][uyna]?)","bepergian{berpergian}%1")
		:gsub("Berkerja([%s%pkmnalt][uyna]?)","Bekerja{Berkerja}%1")
		:gsub("berkerja([%s%pkmnalt][uyna]?)","bekerja{berkerja}%1")
		:gsub("Berterbangan([%s%pkmnalt][uyna]?)","Beterbangan{Berterbangan}%1")
		:gsub("berterbangan([%s%pkmnalt][uyna]?)","beterbangan{berterbangan}%1")
		:gsub("Merubah([%s%pkmnalt][uyna]?)","Mengubah{Merubah = Menjadi rubah}%1")
		:gsub("merubah([%s%pkmnalt][uyna]?)","mengubah{merubah = menjadi rubah}%1")
		:gsub("Dirubah([%s%pkmnalt][uyna]?)","Diubah{Dirubah = Dijadikan rubah}%1")
		:gsub("dirubah([%s%pkmnalt][uyna]?)","diubah{dirubah = dijadikan rubah}%1")
		:gsub("Memerhati([%s%pkmnalt][uyna]?)","Memperhati{Memerhati}%1")
		:gsub("memerhati([%s%pkmnalt][uyna]?)","memperhati{memerhati}%1")
		:gsub("Memeragakan([%s%pkmnalt][uyna]?)","Memperagakan{Memeragakan}%1")
		:gsub("memeragakan([%s%pkmnalt][uyna]?)","memperagakan{memeragakan}%1")
		:gsub("Mempesona([%s%pkmnalt][uyna]?)","Memesona{Mempesona}%1")
		:gsub("mempesona([%s%pkmnalt][uyna]?)","memesona{mempesona}%1")
		:gsub("Memperkosa([%s%pkmnalt][uyna]?)","Memerkosa{Memperkosa}%1")
		:gsub("memperkosa([%s%pkmnalt][uyna]?)","memerkosa{memperkosa}%1")
		:gsub("Mempercayai([%s%pkmnalt][uyna]?)","Memercayai{Mempercayai}%1")
		:gsub("mempercayai([%s%pkmnalt][uyna]?)","memercayai{mempercayai}%1")
		:gsub("Mempengaruhi([%s%pkmnalt][uyna]?)","Memengaruhi{Mempengaruhi}%1")
		:gsub("mempengaruhi([%s%pkmnalt][uyna]?)","memengaruhi{mempengaruhi}%1")
		:gsub("Mempublikasi([%s%pkmnalt][uyna]?)","Memublikasi{Memublikasi}%1")
		:gsub("mempublikasi([%s%pkmnalt][uyna]?)","memublikasi{memublikasi}%1")
		:gsub("Memrogram([%s%pkmnalt][uyna]?)","Memprogram{Memrogram}%1")
		:gsub("memrogram([%s%pkmnalt][uyna]?)","memprogram{memrogram}%1")
		:gsub("Menyukuri([%s%pkmnalt][uyna]?)","Mensyukuri{Menyukuri}%1")
		:gsub("menyukuri([%s%pkmnalt][uyna]?)","mensyukuri{menyukuri}%1")
		:gsub("Memerbaiki([%s%pkmnalt][uyna]?)","Memperbaiki{Memerbaiki}%1")
		:gsub("memerbaiki([%s%pkmnalt][uyna]?)","memperbaiki{memerbaiki}%1")
		:gsub("Menertawa([%s%pkmnalt][uyna]?)","Mentertawa{Menertawa}%1")
		:gsub("menertawa([%s%pkmnalt][uyna]?)","mentertawa{menertawa}%1")
		:gsub("([%s%pkmnalt][egimrnu]?)nterjemah","%1nerjemah{nterjemah}")
		:gsub("Pecinta([%s%pkmnalt][uyna]?))","Pencinta%1")
		:gsub("pecinta([%s%pkmnalt][uyna]?)","pencinta%1")
		:gsub("Pemukiman([%s%pkmnalt][uyna]?)","Permukiman%1")
		:gsub("pemukiman([%s%pkmnalt][uyna]?)","permukiman%1")
		:gsub("Penyewaan([%s%pkmnalt][uyna]?)","Persewaan%1")
		:gsub("penyewaan([%s%pkmnalt][uyna]?)","persewaan%1")
		:gsub("Menyintai([%s%pkmnalt][uyna]?)","Mencintai%1")
		:gsub("menyinta([%s%pkmnalt][uyna]?)","mencintai%1")
		:gsub("Menyolok([%s%pkmnalt][uyna]?)","Mencolok%1")
		:gsub("menyolok([%s%pkmnalt][uyna]?)","mencolok%1")
		:gsub("Menyontek([%s%pkmnalt][uyna]?)","Mencontek%1")
		:gsub("menyontek([%s%pkmnalt][uyna]?)","mencontek%1")
		:gsub("pempr([auieo])","pemp%1")
		:gsub("Pempr([aiueo])","Pemp%1")
		:gsub("Mencat([%s%p])","Mengecat{(Men)cat}%1")
		:gsub("([%s%p])mencat([%s%p])","%1mengecat{(men)cat}%2")

-- Bentuk terikat
		:gsub("Antar ([A-Z])","Antar%-{Antar }%1")
		:gsub(" antar ([A-Z])"," antar%-{ antar }%1")
		:gsub("Antar ([a-z])","Antar%{kalau setelah ini bahasa Inggris, tulis begini: Antar-}%1")
		:gsub(" antar ([a-z])"," antar%{kalau setelah ini bahasa Inggris, tulis begini: antar-}%1")
		:gsub("Sub ([a-z])","Sub%{kalau setelah ini bahasa Inggris, tulis begini: Sub-}%1")
		:gsub(" sub ([a-z])"," sub%{kalau setelah ini bahasa Inggris, tulis begini: sub-}%1")
		:gsub("Pasca ([a-z])","Pasca%{kalau setelah ini bahasa Inggris, tulis begini: Pasca-}%1")
		:gsub(" pasca ([a-z])"," pasca%{kalau setelah ini bahasa Inggris, tulis begini: pasca-}%1")
		:gsub("Serba ([a-z])","Serba%{kalau setelah ini bahasa Inggris, tulis begini: Serba-}%1")
		:gsub(" serba ([a-z])"," serba%{kalau setelah ini bahasa Inggris, tulis begini: serba-}%1")

-- Tempat dan arah
		:gsub("Dimana([%s%pkmnalt][uyna]?)","Di mana{Dimana}%1")
		:gsub(" dimana([%s%pkmnalt][uyna]?)"," di mana{dimana}%1")
		:gsub("Darimana([%s%pkmnalt][uyna]?)","Dari mana{Darimana}%1")
		:gsub(" darimana([%s%pkmnalt][uyna]?)"," dari mana{darimana}%1")
		:gsub("Kemana([%s%pkmnalt][uyna]?)","Ke mana{Kemana}%1")
		:gsub(" kemana([%s%pkmnalt][uyna]?)"," ke mana{kemana}%1")
		:gsub("Diatas([%s%pkmnalt][uyna]?)","Di atas{Diatas}%1")
		:gsub(" diatas([%s%pkmnalt][uyna]?)"," di atas{diatas}%1")
		:gsub("Keatas([%s%pkmnalt][uyna]?)","Ke atas{Keatas}%1")
		:gsub(" keatas([%s%pkmnalt][uyna]?)"," ke atas{keatas}%1")
		:gsub("Dibawah([%s%pkmnalt][uyna]?)","Di bawah{Dibawah}%1")
		:gsub(" dibawah([%s%pkmnalt][uyna]?)"," di bawah{dibawah}%1")
		:gsub("Kebawah([%s%pkmnalt][uyna]?)","Ke bawah{Kebawah}%1")
		:gsub(" kebawah([%s%pkmnalt][uyna]?)"," ke bawah{kebawah}%1")
		:gsub("Didepan([%s%pkmnalt][uyna]?)","Di depan{Didepan}%1")
		:gsub(" didepan([%s%pkmnalt][uyna]?)"," di depan{didepan}%1")
		:gsub("Kedepan([%s%pkmnalt][uyna]?)","Ke depan{Kedepan}%1")
		:gsub(" kedepan([%s%pkmnalt][uyna]?)"," ke depan{kedepan}%1")
		:gsub("Dibelakang([%s%pkmnalt][uyna]?)","Di belakang{Dibelakang}%1")
		:gsub(" dibelakang([%s%pkmnalt][uyna]?)"," di belakang{dibelakang}%1")
		:gsub("Kebelakang([%s%pkmnalt][uyna]?)","Ke belakang{Kebelakang}%1")
		:gsub(" kebelakang([%s%pkmnalt][uyna]?)"," ke belakang{kebelakang}%1")
		:gsub("Dikanan([%s%pkmnalt][uyna]?)","Di kanan{Dikanan}%1")
		:gsub(" dikanan([%s%pkmnalt][uyna]?)"," di kanan{dikanan}%1")
		:gsub("Kekanan([%s%pkmnalt][uyna]?)","Ke kanan{Kekanan}%1")
		:gsub(" kekanan([%s%pkmnalt][uyna]?)"," ke kanan{kekanan}%1")
		:gsub("Dikiri([%s%pkmnalt][uyna]?)","Di kiri{Dikiri}%1")
		:gsub(" dikiri([%s%pkmnalt][uyna]?)"," di kiri{dikiri}%1")
		:gsub("Kekiri([%s%pkmnalt][uyna]?)","Ke kiri{Kekiri}%1")
		:gsub(" kekiri([%s%pkmnalt][uyna]?)"," ke kiri{kekiri}%1")
		:gsub("Disamping([%s%pkmnalt][uyna]?)","Di samping{Disamping}%1")
		:gsub(" disamping([%s%pkmnalt][uyna]?)"," di samping{disamping}%1")
		:gsub("Kesamping([%s%pkmnalt][uyna]?)","Ke samping{Kesamping}%1")
		:gsub(" kesamping([%s%pkmnalt][uyna]?)"," ke samping{kesamping}%1")
		:gsub("Dihadapan([%s%pkmnalt][uyna]?)","Di hadapan{Dihadapan}%1")
		:gsub(" dihadapan([%s%pkmnalt][uyna]?)"," di hadapan{dihadapan}%1")
		:gsub("Disebelah([%s%pmnal][uyna]?)","Di sebelah{Disebelah}%1")
		:gsub(" disebelah([%s%pmnal][uyna]?)"," di sebelah{disebelah}%1")
		:gsub("Kesebelah([%s%pmnal][uyna]?)","Ke sebelah{Kesebelah}%1")
		:gsub(" kesebelah([%s%pmnal][uyna]?)"," ke sebelah{kesebelah}%1")
		:gsub("Disekitar([%s%pmnal][uyna]?)","Di sekitar{Disekitar}%1")
		:gsub(" disekitar([%s%pmnal][uyna]?)"," di sekitar{disekitar}%1")
		:gsub("Ditengah([%s%pmnal][uyna]?)","Di tengah{Ditengah}%1")
		:gsub(" ditengah([%s%pmnal][uyna]?)"," di tengah{ditengah}%1")
		:gsub("Diseluruh([%s%pmnal][uyna]?)","Di seluruh{Diseluruh}%1")
		:gsub(" diseluruh([%s%pmnal][uyna]?)"," di seluruh{diseluruh}%1")
		:gsub("Disaat([%s%pmnal][uyna]?)","Di saat{Disaat}%1")
		:gsub(" disaat([%s%pmnal][uyna]?)"," di saat{disaat}%1")
		:gsub("Dirumah([%s%pmnal][uyna]?)","Di rumah{Dirumah}%1")
		:gsub(" dirumah([%s%pmnal][uyna]?)"," di rumah{dirumah}%1")
		:gsub("Didekat([%s%pmnal][uyna]?)","Di dekat{Didekat}%1")
		:gsub(" didekat([%s%pmnal][uyna]?)"," di dekat{didekat}%1")
		:gsub("Disana([%s%pkmnalt][uyna]?)","Di sana{Disana}%1")
		:gsub(" disana([%s%pkmnalt][uyna]?)"," di sana{disana}%1")
		:gsub("Disini([%s%pkmnalt][uyna]?)","Di sini{Disini}%1")
		:gsub(" disini([%s%pkmnalt][uyna]?)"," di sini{disini}%1")
		:gsub("Disitu([%s%pkmnalt][uyna]?)","Di situ{Disitu}%1")
		:gsub(" disitu([%s%pkmnalt][uyna]?)"," di situ{disitu}%1")

		:gsub("Kesana([%s%pkmnalt][uyna]?)","Ke sana{Kesana}%1")
		:gsub(" kesana([%s%pkmnalt][uyna]?)"," ke sana{kesana}%1")
		:gsub("Kesini([%s%pkmnalt][uyna]?)","Ke sini{Kesini}%1")
		:gsub(" kesini([%s%pkmnalt][uyna]?)"," ke sini{kesini}%1")
		:gsub("Kesitu([%s%pkmnalt][uyna]?)","Ke situ{Kesitu}%1")
		:gsub(" kesitu([%s%pkmnalt][uyna]?)"," ke situ{kesitu}%1")

		:gsub("Diawal([%s%pkmnalt][uyna]?)","Di awal{Diawal}%1")
		:gsub(" diawal([%s%pkmnalt][uyna]?)"," di awal{diawal}%1")
		:gsub("Diakhir([%s%pkmnalt][uyna]?)","Di akhir{Diakhir}%1")
		:gsub(" diakhir([%s%pkmnalt][uyna]?)"," di akhir{diakhir}%1")
		:gsub("Diantara([%s%pkmnalt][uyna]?)","Di antara{Diantara}%1")
		:gsub(" diantara([%s%pkmnalt][uyna]?)"," di antara{diantara}%1")
		:gsub("Diluar([%s%pkmnalt][uyna]?)","Di luar{Diluar}%1")
		:gsub(" diluar([%s%pkmnalt][uyna]?)"," di luar{diluar}%1")
		:gsub("Didalam([%s%pkmnalt][uyna]?)","Di dalam{Didalam}%1")
		:gsub(" didalam([%s%pkmnalt][uyna]?)"," di dalam{didalam}%1")
		:gsub("Kedalaman","Ke{}dalaman")
		:gsub(" kedalaman"," ke{}dalaman")
		:gsub("Kedalam([%s%pkmnalt][uyna]?)","Ke dalam{Kedalam}%1")
		:gsub(" kedalam([%s%pkmnalt][uyna]?)"," ke dalam{kedalam}%1")

-- Serangkai dan terpisah
		:gsub("Ada kalanya([%s%p])","Adakalanya{Ada kalanya}%1")
		:gsub(" ada kalanya([%s%p])"," adakalanya{ ada kalanya}%1")
		:gsub("Apa bila([%s%p])","Apabila{Apa bila}%1")
		:gsub(" apa bila([%s%p])"," apabila{ apa bila}%1")
		:gsub("Bagai mana([%s%pkmnalt])","Bagaimana{Bagai mana}%1")
		:gsub(" bagai mana([%s%pkmnalt])"," bagaimana{ bagai mana}%1")
		:gsub("Bela sungkawa([%s%pkmnalt])","Belasungkawa{Bela sungkawa}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)bela sungkawa"," belasungkawa{bela sungkawa}%1")
		:gsub("Dari pada([%s%pkmnalt])","Daripada{Dari pada}%1")
		:gsub(" dari pada([%s%pkmnalt])"," daripada{ dari pada}%1")
		:gsub("Duka cita([%s%pkmnalt])","Dukacita{Duka cita}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)duka cita","%1dukacita{duka cita}")
		:gsub("Kaca mata([%s%pkmnalt])","Kacamata{Kaca mata}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)kaca mata","%1kacamata{kaca mata}")
		:gsub("Kasat mata([%s%pkmnalt])","Kasatmata{Kasat mata}%1")
		:gsub(" kasat mata([%s%pkmnalt])"," kasatmata{ kasat mata}%1")
		:gsub("Mana kala([%s%pkmnalt])","Manakala{Mana kala}%1")
		:gsub(" mana kala([%s%pkmnalt])"," manakala{ mana kala}%1")
		:gsub("Olah raga([%s%pkmnalt])","Olahraga{Olah raga}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)olah raga","%1olahraga{olah raga}")
		:gsub("Sari pati([%s%pkmnalt])","Saripati{Sari pati}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)saripati","%1saripati{sari pati}")
		:gsub("Sebagai mana([%s%pkmnalt])","Sebagaimana{Sebagai mana}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sebagai mana","%1sebagaimana{sebagai mana}")
		:gsub("Sedia kala([%s%pkmnalt])","Sediakala{Sedia kala}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)sedia kala","%1sediakala{sedia kala}")
		:gsub("Suka cita([%s%pkmnalt])","Sukacita{Suka cita}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)suka cita","%1sukacita{suka cita}")
		:gsub("Suka rela([%s%pkmnalt])","Sukarela{Suka rela}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)suka rela","%1sukarela{suka rela}")
		:gsub("Suka ria([%s%pkmnalt])","Sukaria{Suka ria}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)suka ria","%1sukaria{suka ria}")
		:gsub("Wali kota([%s%pkmnalt])","Walikota{Wali kota}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)wali kota","%1walikota{wali kota}")
		:gsub("Terimakasih([%s%pkmnalt])","Terima kasih{terimakasih}%1")
		:gsub("([%s%-mndpekat][egimrnu]?)terimakasih","%1terima kasih{terimakasih}")
		:gsub("([a-z])terima kasih([kmnal])","%1terimakasih{terima kasih}")
		:gsub("([%s%-mndpekat][egimrnu]?)wali kota","%1walikota{wali kota}")
		:gsub("{terima kasih}{terimakasih}","{terima kasih}")
		:gsub("Ibu kota([%s%pkmnalt][uyna]?)","Ibukota{Ibu kota}%1")
		:gsub(" ibu kota([%s%pkmnalt][uyna]?)"," ibukota{ibu kota}%1")
		:gsub("([a-z])alih tugas([kmnal])","%1alihtugas{alih tugas}")
		:gsub("([a-z])beri tahu([kmnal])","%1beritahu{beri tahu}")
		:gsub("([a-z])hancur lebur tahu([kmnal])","%1hancurlebur{hancur lebur}")
		:gsub("([a-z])kerja sama([kmnal])","%1kerjasama{kerja sama}")
		:gsub("([a-z])kambing hitam([kmnal])","%1kambinghitam{kambing hitam}")
		:gsub("([a-z])gambing hitam([kmnal])","%1gambinghitam{gambing hitam}")
		:gsub("([a-z])tanda tangan([kmnal])","%1tandatangan{tanda tangan}")
		:gsub("([a-z])nanda tangan([kmnal])","%1nandatangan{nanda tangan}")
		:gsub("([a-z])tanggung jawab([kmnal])","%1tanggungjawab{tanggung jawab}")
		:gsub("([a-z])nanggung jawab([kmnal])","%1nanggungjawab{nanggung jawab}")
		:gsub("([a-z])nyalah guna([kmnal])","%1nyalahguna{nyalah guna}")

-- Partikel 'pun'
		:gsub("Bagaimana pun([%s%pkmnalt][uyna]?)","Bagaimanapun{Bagaimana pun}%1")
		:gsub("bagaimana pun([%s%pkmnalt][uyna]?)","bagaimanapun{bagaimana pun}%1")
		:gsub("Siapapun([%s%pkmnalt][uyna]?)","Siapa pun{(Siapa)pun}%1")
		:gsub("siapapun([%s%pkmnalt][uyna]?)","siapa pun{(siapa)pun}%1")
		:gsub("Berapapun([%s%pkmnalt][uyna]?)","Berapa pun{Berapapun}%1")
		:gsub("berapapun([%s%pkmnalt][uyna]?)","berapa pun{berapapun}%1")
		:gsub("Inipun([%s%pkmnalt][uyna]?)","Ini pun{Ini pun}%1")
		:gsub("inipun([%s%pkmnalt][uyna]?)","ini pun{ini pun}%1")
		:gsub("Itupun([%s%pkmnalt][uyna]?)","Itu pun{Itu pun}%1")
		:gsub("itupun([%s%pkmnalt][uyna]?)","itu pun{itu pun}%1")
		:gsub("Ada pun([%s%pkmnalt][uyna]?)","Adapun{Ada pun}%1")
		:gsub("ada pun([%s%pkmnalt][uyna]?)","adapun{ada pun}%1")
		:gsub("Biar pun([%s%pkmnalt][uyna]?)","Biarpun{Biar pun}%1")
		:gsub("biar pun([%s%pkmnalt][uyna]?)","biarpun{biar pun}%1")
		:gsub("Atau pun([%s%pkmnalt][uyna]?)","Ataupun{Atau pun}%1")
		:gsub("atau pun([%s%pkmnalt][uyna]?)","ataupun{atau pun}%1")
		:gsub("Kalau pun([%s%pkmnalt][uyna]?)","Kalaupun{Kalau pun}%1")
		:gsub("kalau pun([%s%pkmnalt][uyna]?)","kalaupun{kalau pun}%1")
		:gsub("Meski pun([%s%pkmnalt][uyna]?)","Meskipun{Meski pun}%1")
		:gsub("meski pun([%s%pkmnalt][uyna]?)","meskipun{meski pun}%1")
		:gsub("Mau pun([%s%pkmnalt][uyna]?)","Maupun{Mau pun}%1")
		:gsub("mau pun([%s%pkmnalt][uyna]?)","maupun{mau pun}%1")
		:gsub("Walau pun([%s%pkmnalt][uyna]?)","Walaupun{Walau pun}%1")
		:gsub("walau pun([%s%pkmnalt][uyna]?)","walaupun{walau pun}%1")
		:gsub("Kapanpun([%s%pkmnalt][uyna]?)","Kapan pun{Kapanpun}%1")
		:gsub("kapanpun([%s%pkmnalt][uyna]?)","kapan pun{kapanpun}%1")
		:gsub("Apapun([%s%pkmnalt][uyna]?)","Apa pun{Apapun}%1")
		:gsub("apapun([%s%pkmnalt][uyna]?)","apa pun{apapun}%1")
		:gsub("Di manapun([%s%pkmnalt][uyna]?)","Di mana pun{Di manapun}%1")
		:gsub("di manapun([%s%pkmnalt][uyna]?)","di mana pun{di manapun}%1")
		:gsub("Dimanapun([%s%pkmnalt][uyna]?)","Di mana pun{Dimanapun}%1")
		:gsub("dimanapun([%s%pkmnalt][uyna]?)","di mana pun{dimanapun}%1")
		:gsub("Dari manapun([%s%pkmnalt][uyna]?)","Dari mana pun{Dari manapun}%1")
		:gsub("dari manapun([%s%pkmnalt][uyna]?)","dari mana pun{dari manapun}%1")
		:gsub("Darimanapun([%s%pkmnalt][uyna]?)","Dari mana pun{Darimanapun}%1")
		:gsub("darimanapun([%s%pkmnalt][uyna]?)","dari mana pun{darimanapun}%1")
		:gsub(" manapun([%s%pkmnalt][uyna]?)"," mana pun{ manapun}%1")

-- Tanda koma
		:gsub("Oleh karena itu ","Oleh karena itu{}, ")
		:gsub("Padahal ","Padahal{}, ")
		:gsub("Kemudian ","Kemudian{}, ")
		:gsub("Lalu ","Lalu{}, ")
		:gsub("Karena itu ","Karena itu{}, ")
		:gsub("Oleh karena itu ","Oleh karena itu{}, ")
		:gsub("Dengan begitu ","Dengan begitu{}, ")
		:gsub("Sebelum itu ","Sebelum itu{}, ")
		:gsub("Sebelum ini ","Sebelum ini{}, ")
		:gsub("Sebelumnya ","Sebelumnya{}, ")
		:gsub("Sesudah itu ","Sesudah itu{}, ")
		:gsub("Sesudah ini ","Sesudah ini{}, ")
		:gsub("Sesudahnya ","Sesudahnya{}, ")
		:gsub("Malah ","Malah{}, ")
		:gsub("Oleh sebab itu ","Oleh sebab itu{}, ")
		:gsub("Meskipun begitu ","Meskipun begitu itu{}, ")
		:gsub("Meski begitu ","Meski begitu itu{}, ")
		:gsub("Meskipun, ","Meskipun ")
		:gsub("meskipun, ","meskipun ")
		:gsub("Lagi pula ","Lagi pula{}, ")
		:gsub("Lagipula ","Lagi pula{}, ")
		:gsub("Kalau begitu ","Kalau begitu{}, ")
		:gsub("Selain itu ","Selain itu{}, ")
		:gsub("Bahkan ","Bahkan{}, ")
		:gsub("Namun ","Namun{}, ")
		:gsub(", bahwa","{} bahwa")
		:gsub(", agar","{} agar")
		:gsub(", karena","{} karena")
		:gsub(", agar","{} agar")
		:gsub(", sehingga","{} sehingga")
		:gsub(", supaya","{} supaya")
		:gsub(", jika","{} jika")
		:gsub(", apabila","{} apabila")

-- Kata ulang
		:gsub("([AIUEO])%-([AIUEO])","%1%-%2\"\"")
		:gsub(" ([aiueo])%-([aiueo])"," %1%-%2\"\"")
		:gsub("(%u)%-(%u)([aiueoyj])","%1%3%-%2%3")
		:gsub("(%u)%-(%u)([rlswpthkznm])([aiueoyj])","%1%3%4%-%2%3%4")
		:gsub("([%s%p])(%l)%-(%l)([aiueoyj])","%1%2%4%-%3%4")
		:gsub("([%s%p])(%l)%-(%l)([rlswpthkznm])([aiueoyj])","%1%2%4%5%-%3%4%5")
		:gsub("%-Itu%-Itu","%-I%-Itu")
		:gsub("%-itu%-itu","%-i%-itu")
		:gsub("%-Ini%-Ini","%-I%-Ini")
		:gsub("%-ini%-ini","%-i%-ini")
		:gsub("\"\"","")
		:gsub("Ya-Ya","Y-Ya")

-- Kata seru
		:gsub("Aduh( ?%.?%.?%.?) (%a)","Aduh%1, %2")
		:gsub("([%a}\"\"]) aduh([%s%p])","%1, aduh%2")
		:gsub(" aduh( ?%.?%.?%.?) (%a)"," aduh%1, %2")

		:gsub("Waw( ?%.?%.?%.?) (%a)","Wo{}w{W(a)w}%1, %2")
		:gsub("([%a}\"\"]) waw([%s%p])","%1, wo{}w{w(a)w}%2")
		:gsub(" waw( ?%.?%.?%.?) (%a)"," wo{}w{w(a)w}%1, %2")
		:gsub("Waw([%s%p])","Wo{}w{W(a)w}%1")
		:gsub("waw([%s%p])","wo{}w{w(a)w}%1")

		:gsub("Aw( ?%.?%.?%.?) (%a)","Aduh{A(w)}%1, %2")
		:gsub("([%a}\"\"]) aw([%s%p])","%1, aduh{a(w)}%2")
		:gsub(" aw( ?%.?%.?%.?) (%a)"," aduh{a(w)}%1, %2")
		:gsub("Aw([%s%p])","Aduh{A(w)}%1")
		:gsub("aw([%s%p])","aduh{a(w)}%1")

		:gsub("Wow( ?%.?%.?%.?) (%a)","Wo{}w%1, %2")
		:gsub("([%a}\"\"]) wow([%s%p])","%1, wo{}w%2")
		:gsub(" wow( ?%.?%.?%.?) (%a)"," wo{}w%1, %2")
		:gsub("Wow([%s%p])","Wo{}w%1")
		:gsub("wow([%s%p])","wo{}w%1")

		:gsub("Ow( ?%.?%.?%.?) (%a)","Aduh{O(w)}%1, %2")
		:gsub("([%a}\"\"]) ow([%s%p])","%1, aduh{o(w)}%2")
		:gsub(" ow( ?%.?%.?%.?) (%a)"," aduh{o(w)}%1, %2")
		:gsub("Ow([%s%p])","Aduh{O(w)}%1")
		:gsub("ow([%s%p])","aduh{o(w)}%1")

		:gsub("Aww( ?%.?%.?%.?) (%a)","Aduh{A(ww)}%1, %2")
		:gsub("([%a}\"\"]) aww([%s%p])","%1, aduh{a(ww)}%2")
		:gsub(" aww( ?%.?%.?%.?) (%a)"," aduh{a(ww)}%1, %2")
		:gsub("Aww([%s%p])","Aduh{A(ww)}%1")
		:gsub("aww([%s%p])","aduh{a(ww)}%1")

		:gsub("Ouch( ?%.?%.?%.?) (%a)","Aduh{O(uch)}%1, %2")
		:gsub("([%a}\"\"]) ouch([%s%p])","%1, aduh{o(uch)}%2")
		:gsub(" ouch( ?%.?%.?%.?) (%a)"," aduh{o(uch)}%1, %2")
		:gsub("Ouch([%s%p])","Aduh{O(uch)}%1")
		:gsub("ouch([%s%p])","aduh{o(uch)}%1")

		:gsub("Um( ?%.?%.?%.?) (%a)","Anu{U(m)}%1, %2")
		:gsub("([%a}\"\"]) um([%s%p])","%1, anu{u(m)}")
		:gsub(" um( ?%.?%.?%.?) (%a)"," anu{u(m)}%1, %2")
		:gsub("Um([%s%p])","Anu{U(m)}%1")
		:gsub(" um([%s%p])"," anu{u(m)}%1")
		:gsub("Um([%s%p])","Anu{U(m)}%1")

		:gsub("Ano( ?%.?%.?%.?) (%a)","Anu{A(no)}%1, %2")
		:gsub("([%a}\"\"]) ano([%s%p])","%1, anu{a(no)}%2")
		:gsub(" ano( ?%.?%.?%.?) (%a)"," anu{a(no)}%1, %2")
		:gsub("Ano([%s%p])","Anu{A(no)}%1")
		:gsub(" ano([%s%p])"," anu{a(no)}%1")
		:gsub("Ano([%s%p])","Anu{A(no)}%1")

		:gsub("Anu( ?%.?%.?%.?) (%a)","Anu%1, %2")
		:gsub("([%a}\"\"]) anu([%s%p])","%1, anu%2")
		:gsub(" anu( ?%.?%.?%.?) (%a)"," anu%1, %2")

		:gsub("Ahh( ?%.?%.?%.?) (%a)","Ah{A(hh)}%1, %2")
		:gsub("ahh( ?%.?%.?%.?) (%a)","ah{a(hh)}%1, %2")
		:gsub("Ahh([%s%p])","Ah{A(hh)}%1")
		:gsub(" ahh([%s%p])"," ah{a(hh)}%1")

		:gsub("Ah( ?%.?%.?%.?) (%a)","Ah%1, %2")
		:gsub("([%a}\"\"]) ah([%s%p])","%1, ah%2")
		:gsub(" ah( ?%.?%.?%.?) (%a)"," ah%1, %2")

		:gsub("Alah( ?%.?%.?%.?) (%a)","Alah%1, %2")
		:gsub("([%a}\"\"]) alah([%s%p])","%1, alah%2")
		:gsub(" alah( ?%.?%.?%.?) (%a)"," alah%1, %2")

		:gsub("Bah( ?%.?%.?%.?) (%a)","Bah%1, %2")
		:gsub("([%a}\"\"]) bah([%s%p])","%1, bah%2")
		:gsub(" bah( ?%.?%.?%.?) (%a)"," bah%1, %2")

		:gsub("Tch( ?%.?%.?%.?) (%a)","Cih%1{T(ch)}, %2")
		:gsub("([%a}\"\"]) tch([%s%p])","%1, cih{t(ch)}%2")
		:gsub(" tch( ?%.?%.?%.?) (%a)"," cih{t(ch)}%1, %2")
		:gsub("Tch([%s%p])","Cih{T(ch)}%1")
		:gsub("tch([%s%p])","cih{t(ch)}%1")

		:gsub("Cih( ?%.?%.?%.?) (%a)","Cih%1, %2")
		:gsub("([%a}\"\"]) cih([%s%p])","%1, cih%2")
		:gsub(" cih( ?%.?%.?%.?) (%a)"," cih%1, %2")

		:gsub("Eh( ?%.?%.?%.?) (%a)","Eh%1, %2")
		:gsub("([%a}\"\"]) eh([%s%p])","%1, eh%2")
		:gsub(" eh( ?%.?%.?%.?) (%a)"," eh%1, %2")

		:gsub("Eh(h?h?h?h?h?)","Eh{%1}")
		:gsub(" eh(h?h?h?h?h?)"," eh{%1}")

		:gsub("Etto( ?%.?%.?%.?) (%a)","Hem{E(tto)}%1, %2")
		:gsub("([%a}\"\"]) etto([%s%p])","%1, hem{e(tto)}%2")
		:gsub(" etto( ?%.?%.?%.?) (%a)"," hem{e(tto)}%1, %2")
		:gsub("Etto([%s%p])","Hem{E(tto)}%1")
		:gsub("etto([%s%p])","hem{e(tto)}%1")

		:gsub("Halo( ?%.?%.?%.?) (%a)","Halo%1, %2")
		:gsub("([%a}\"\"]) halo([%s%p])","%1, halo%2")
		:gsub(" halo( ?%.?%.?%.?) (%a)"," halo%1, %2")

		:gsub("Ha( ?%.?%.?%.?) (%a)","Ha%1, %2")
		:gsub("([%a}\"\"]) ha([%s%p])","%1, ha%2")
		:gsub(" ha( ?%.?%.?%.?) (%a)"," ha%1, %2")

		:gsub("He( ?%.?%.?%.?) (%a)","He%1, %2")
		:gsub("([%a}\"\"]) he([%s%p])","%1, he%2")
		:gsub(" he( ?%.?%.?%.?) (%a)"," he%1, %2")

		:gsub("Hai( ?%.?%.?%.?) (%a)","Hai%1, %2")
		:gsub("([%a}\"\"]) hai([%s%p])","%1, hai%2")
		:gsub(" hai( ?%.?%.?%.?) (%a)"," hai%1, %2")

		:gsub("Iya ","Iya, ")
		:gsub(" iya "," iya, ")

		:gsub("Hey( ?%.?%.?%.?) (%a)","He{He(y)}%1, %2")
		:gsub("([%a}\"\"]) hey([%s%p])","%1, he{he(y)}%2")
		:gsub(" hey( ?%.?%.?%.?) (%a)"," he{he(y)}%1, %2")
		:gsub("Hey([%s%p])","He{He(y)}%1")
		:gsub("hey([%s%p])","he{he(y)}%1")

		:gsub("Hei( ?%.?%.?%.?) (%a)","He{He(i)}%1, %2")
		:gsub("([%a}\"\"]) hei([%s%p])","%1, he{he(i)}")
		:gsub(" hei( ?%.?%.?%.?) (%a)"," he{he(i)}%1, %2")
		:gsub("Hei([%s%p])","He{He(i)}%1")
		:gsub("hei([%s%p])","he{he(i)}%1")


		:gsub("Hmm( ?%.?%.?%.?) (%a)","Hem{H(mm)}%1, %2")
		:gsub("([%a}\"\"]) hm([%s%p])","%1, hem{h(mm)}%2")
		:gsub(" hmm( ?%.?%.?%.?) (%a)"," hem{h(mm)}%1, %2")
		:gsub("Hmm([%s%p])","Hem{H(mm)}%1")
		:gsub("hmm([%s%p])","hem{h(mm)}%1")

		:gsub("Mm( ?%.?%.?%.?) (%a)","Hem{M(m)}%1, %2")
		:gsub("([%a}\"\"]) mm([%s%p])","%1, hem{m(m)}%2")
		:gsub(" mm( ?%.?%.?%.?) (%a)"," hem{m(m)}%1, %2")
		:gsub("Mm([%s%p])","Hem{M(m)}%1")
		:gsub(" mm([%s%p])"," hem{m(m)}%1")


		:gsub("Mmm( ?%.?%.?%.?) (%a)","Hem{M(mm)}%1, %2")
		:gsub("([%a}\"\"]) hm([%s%p])","%1, hem{m(mm)}%2")
		:gsub(" mmm( ?%.?%.?%.?) (%a)"," hem{m(mm)}%1, %2")
		:gsub("Mmm([%s%p])","Hem{M(mm)}%1")
		:gsub(" mmm([%s%p])"," hem{m(mm)}%1")

		:gsub("Hmmm( ?%.?%.?%.?) (%a)","Hem{H(mmm)}%1, %2")
		:gsub("([%a}\"\"]) hm([%s%p])","%1, hem{h(mmm)}%2")
		:gsub(" hmmm( ?%.?%.?%.?) (%a)"," hem{h(mmm)}%1, %2")
		:gsub("Hmmm([%s%p])","Hem{H(mmm)}%1")
		:gsub("hmmm([%s%p])","hem{h(mmm)}%1")

		:gsub("Hm( ?%.?%.?%.?) (%a)","Hem{H(m)}%1, %2")
		:gsub("([%a}\"\"]) hm([%s%p])","%1, hem{h(m)}%2")
		:gsub(" hm( ?%.?%.?%.?) (%a)"," hem{h(m)}%1, %2")
		:gsub("Hm([%s%p])","Hem{H(m)}%1")
		:gsub(" hm([%s%p])"," hem{h(m)}%1")

		:gsub("Hem( ?%.?%.?%.?) (%a)","Hem%1, %2")
		:gsub("([%a}\"\"]) hem([%s%p])","%1, hem%2")
		:gsub(" hem( ?%.?%.?%.?) (%a)"," hem%1, %2")

		:gsub("Hi( ?%.?%.?%.?) (%a)","Hi%1, %2")
		:gsub("([%a}\"\"]) hi([%s%p])","%1, hi%2")
		:gsub(" hi( ?%.?%.?%.?) (%a)"," hi%1, %2")

		:gsub("His( ?%.?%.?%.?) (%a)","His%1, %2")
		:gsub("([%a}\"\"]) his([%s%p])","%1, his%2")
		:gsub(" his( ?%.?%.?%.?) (%a)"," his%1, %2")

		:gsub("Hoi( ?%.?%.?%.?) (%a)","Hoi%1, %2")
		:gsub("([%a}\"\"]) hoi([%s%p])","%1, hoi%2")
		:gsub(" hoi( ?%.?%.?%.?) (%a)"," hoi%1, %2")

		:gsub("Hore( ?%.?%.?%.?) (%a)","Hore%1, %2")
		:gsub("([%a}\"\"]) hore([%s%p])","%1, hore%2")
		:gsub(" hore( ?%.?%.?%.?) (%a)"," hore%1, %2")

		:gsub("Hus( ?%.?%.?%.?) (%a)","Hus%1, %2")
		:gsub("([%a}\"\"]) hus([%s%p])","%1, hus%2")
		:gsub(" hus( ?%.?%.?%.?) (%a)"," hus%1, %2")

		:gsub("Deh( ?%.?%.?%.?) (%a)","Deh{D(a)h}%1, %2")
		:gsub("([%a}\"\"]) deh([%s%p])","%1, deh{d(a)h}%2")
		:gsub(" deh( ?%.?%.?%.?) (%a)"," deh{d(a)h}%1, %2")

		:gsub("Dah( ?%.?%.?%.?) (%a)","Deh%1, %2")
		:gsub("([%a}\"\"]) dah([%s%p])","%1, deh%2")
		:gsub(" dah( ?%.?%.?%.?) (%a)"," deh%1, %2")

		:gsub("Dih( ?%.?%.?%.?) (%a)","Ih{D(ih)}%1, %2")
		:gsub("([%a}\"\"]) dih([%s%p])","%1, ih{d(ih)}%2")
		:gsub(" dih( ?%.?%.?%.?) (%a)"," ih{d(ih)}%1, %2")
		:gsub("Idih( ?%.?%.?%.?) (%a)","Ih{Id(ih)}%1, %2")
		:gsub("([%a}\"\"]) idih([%s%p])","%1, ih{id(ih)}")
		:gsub(" idih( ?%.?%.?%.?) (%a)"," ih{id(ih)}%1, %2")
		:gsub("Ih( ?%.?%.?%.?) (%a)","Ih%1, %2")
		:gsub("([%a}\"\"]) ih([%s%p])","%1, ih%2")
		:gsub(" ih( ?%.?%.?%.?) (%a)"," ih%1, %2")
		:gsub("Dih([%s%p])","Ih{D(ih)}%1")
		:gsub(" dih([%s%p])"," ih{d(ih)}%1")
		:gsub("Idih([%s%p])","Ih{Id(ih)}%1")
		:gsub(" idih([%s%p])"," ih{id(ih)}%1")


		:gsub(" \'kan %.%.%. (%a)","{,} \'kan %.%.%.{,} %1")
		:gsub(" \'kan %.%.%. ([%?%!%.])",", \'kan %.%.%.%1")

		:gsub(" kan %.%.%. (%a)","{,} kan %.%.%.{,} %1")
		:gsub(" kan %.%.%. ([%?%!%.])",", kan %.%.%.%1")

		:gsub("Kan%.","Kan%?")
		:gsub("Kan %.%.%.%.","Kan %.%.%.%?")
		:gsub("{,}{,}","{,}")
		:gsub(",{,}",",")

		:gsub(" (\'?)kan%.",", %1kan%?")
		:gsub(" (\'?)kan%?",", %1kan%?")
		:gsub(" (\'?)kan%!",", %1kan%?")
		:gsub(" (\'?)kan %.%.%.%.",", %1kan %.%.%.%?")

		:gsub("(%a) kok([%p])","%1, kok%2")
		:gsub("([%a}\"\"]) kok([%s%p])","%1{,} kok%2")
		:gsub(" kok( ?%.?%.?%.?) (%a)"," kok%1{,} %2")
		:gsub(" kok( ?%.?%.?%.?) ([%?%!%.])",", kok%1 %2")

		:gsub("\'Lah( ?%.?%.?%.?) (%a)","Lah%1, %2")
		:gsub("([%a}\"\"]) \'lah([%s%p])","%1, lah%2")
		:gsub(" \'lah( ?%.?%.?%.?) (%a)"," lah%1, %2")

		:gsub("Lah( ?%.?%.?%.?) (%a)","Lah%1, %2")
		:gsub("([%a}\"\"]) lah([%s%p])","%1, lah%2")
		:gsub(" lah( ?%.?%.?%.?) (%a)"," lah%1, %2")

		:gsub("Yosh( ?%.?%.?%.?) (%a)","Baiklah{Yos(h)}%1, %2")
		:gsub("([%a}\"\"]) yosh([%s%p])","%1{}, baiklah{yos(h)}%2")
		:gsub(" yosh( ?%.?%.?%.?) (%a)"," baiklah{yos(h)}%1, %2")
		:gsub("Yosh([%s%p])","Baiklah{Yos(h)}%1")
		:gsub("yosh([%s%p])","baiklah{yos(h)}%1")

		:gsub("Yosha( ?%.?%.?%.?) (%a)","Baiklah{Yos(ha)}%1, %2")
		:gsub("([%a}\"\"]) yosh([%s%p])","%1{}, baiklah{yos(ha)}%2")
		:gsub(" yosha( ?%.?%.?%.?) (%a)"," baiklah{yos(ha)}%1, %2")
		:gsub("Yosha([%s%p])","Baiklah{Yos(ha)}%1")
		:gsub("yosha([%s%p])","baiklah{yos(ha)}%1")

		:gsub("Yossha( ?%.?%.?%.?) (%a)","Baiklah{Yoss(ha)}%1, %2")
		:gsub("([%a}\"\"]) yosh([%s%p])","%1{}, baiklah{yoss(ha)}%2")
		:gsub(" yossha( ?%.?%.?%.?) (%a)"," baiklah{yoss(ha)}%1, %2")
		:gsub("Yossha([%s%p])","Baiklah{Yoss(ha)}%1")
		:gsub("yossha([%s%p])","baiklah{yoss(ha)}%1")

		:gsub("Lho( ?%.?%.?%.?) (%a)","Lo{L(h)o}%1, %2")
		:gsub("([%a}\"\"]) lho([%s%p])","%1{}, lo{l(h)o}%2")
		:gsub(" lho( ?%.?%.?%.?) (%a)"," lo{l(h)o}%1, %2")
		:gsub("Lho([%s%p])","Lo{L(h)o}%1")
		:gsub("lho([%s%p])","lo{l(h)o}%1")

		:gsub("Loh( ?%.?%.?%.?) (%a)","Lo{Lo(h)}%1, %2")
		:gsub("([%a}\"\"]) lho([%s%p])","%1{}, lo{lo(h)}%2")
		:gsub(" loh( ?%.?%.?%.?) (%a)"," lo{lo(h)}%1, %2")
		:gsub("Loh([%s%p])","Lo{Lo(h)}%1")
		:gsub("loh([%s%p])","lo{lo(h)}%1")


		:gsub("Lo( ?%.?%.?%.?) (%a)","Lo%1, %2")
		:gsub("([%a}\"\"]) lo([%s%p])","%1, lo%2")
		:gsub(" lo( ?%.?%.?%.?) (%a)"," lo%1, %2")

		:gsub("([%a}\"\"]) dong([%s%p])","%1, dong%2")
		:gsub(" dong( ?%.?%.?%.?) (%a)"," dong%1, %2")

		:gsub("Nah( ?%.?%.?%.?) (%a)","Nah%1, %2")
		:gsub("([%a}\"\"]) nah([%s%p])","%1, nah%2")
		:gsub(" nah( ?%.?%.?%.?) (%a)"," nah%1, %2")

		:gsub("Nih( ?%.?%.?%.?) (%a)","Nih%1, %2")
		:gsub("([%a}\"\"]) nih([%s%p])","%1, nih%2")
		:gsub(" nih( ?%.?%.?%.?) (%a)"," nih%1, %2")
		
		:gsub("Noh( ?%.?%.?%.?) (%a)","Noh%1, %2")
		:gsub("([%a}\"\"]) noh([%s%p])","%1, noh%2")
		:gsub(" noh( ?%.?%.?%.?) (%a)"," noh%1, %2")

		:gsub("Tuh( ?%.?%.?%.?) (%a)","Tuh%1, %2")
		:gsub("([%a}\"\"]) tuh([%s%p])","%1, tuh%2")
		:gsub(" tuh( ?%.?%.?%.?) (%a)"," tuh%1, %2")

		:gsub("Oh( ?%.?%.?%.?) (%a)","Oh%1, %2")
		:gsub("([%a}\"\"]) oh([%s%p])","%1, oh%2")
		:gsub(" oh( ?%.?%.?%.?) (%a)"," oh%1, %2")

		:gsub("Woi( ?%.?%.?%.?) (%a)","Oi{(W)oi}%1, %2")
		:gsub("([%a}\"\"]) woi([%s%p])","%1, oi{(w)oi}%2")
		:gsub(" woi( ?%.?%.?%.?) (%a)"," oi{(w)oi}%1, %2")
		:gsub("Woy( ?%.?%.?%.?) (%a)","Oi{(W)oy}%1, %2")
		:gsub("([%a}\"\"]) woy([%s%p])","%1, oi{(w)oy}%2")
		:gsub(" woy( ?%.?%.?%.?) (%a)"," oi{(w)oy}%1, %2")
		:gsub("Oi( ?%.?%.?%.?) (%a)","Oi%1, %2")
		:gsub("([%a}\"\"]) oi([%s%p])","%1, oi%2")
		:gsub(" oi( ?%.?%.?%.?) (%a)"," oi%1, %2")
		:gsub("Woi([%s%p])","Oi{(W)oi}%1")
		:gsub("woi([%s%p])","oi{(w)oi}%1")
		:gsub("Woy([%s%p])","Oi{(W)oy}%1")
		:gsub("woy([%s%p])","oi{(w)oy}%1")

		:gsub("Ugh( ?%.?%.?%.?) (%a)","Uh{U(g)h}%1, %2")
		:gsub("([%a}\"\"]) ugh([%s%p])","%1, uh{u(g)h}%2")
		:gsub(" ugh( ?%.?%.?%.?) (%a)"," uh{u(g)h}%1, %2")
		:gsub("Uh( ?%.?%.?%.?) (%a)","Uh%1, %2")
		:gsub("([%a}\"\"]) uh([%s%p])","%1, uh%2")
		:gsub(" uh( ?%.?%.?%.?) (%a)"," uh%1, %2")
		:gsub("Ugh([%s%p])","Uh{U(g)h}%1")
		:gsub("ugh([%s%p])","uh{u(g)h}%1")

		:gsub("Waduh( ?%.?%.?%.?) (%a)","Waduh%1, %2")
		:gsub("([%a}\"\"]) waduh([%s%p])","%1, waduh%2")
		:gsub(" waduh( ?%.?%.?%.?) (%a)"," waduh%1, %2")

		:gsub("Wah( ?%.?%.?%.?) (%a)","Wah%1, %2")
		:gsub("([%a}\"\"]) wah([%s%p])","%1, wah%2")
		:gsub(" wah( ?%.?%.?%.?) (%a)"," wah%1, %2")

		:gsub("Walah( ?%.?%.?%.?) (%a)","Walah%1, %2")
		:gsub("([%a}\"\"]) walah([%s%p])","%1, walah%2")
		:gsub(" walah( ?%.?%.?%.?) (%a)"," walah%1, %2")

		:gsub("Wai( ?%.?%.?%.?) (%a)","Wai%1, %2")
		:gsub("([%a}\"\"]) wai([%s%p])","%1, wai%2")
		:gsub(" wai( ?%.?%.?%.?) (%a)"," wai%1, %2")

		:gsub("Wih( ?%.?%.?%.?) (%a)","Weh{W(i)h}%1, %2")
		:gsub("([%a}\"\"]) wih([%s%p])","%1{}, weh{w(i)h}%2")
		:gsub(" wih( ?%.?%.?%.?) (%a)"," weh{w(i)h}%1, %2")
		:gsub("Wih([%s%p])","Weh{W(i)h}%1")
		:gsub("wih([%s%p])","weh{w(i)h}%1")

		:gsub("Widih( ?%.?%.?%.?) (%a)","Weh%1, %2")
		:gsub("([%a}\"\"]) widih([%s%p])","%1, weh%2")
		:gsub(" widih( ?%.?%.?%.?) (%a)"," weh%1, %2")
		:gsub("Widih(%p)","Weh{Wih}%1")
		:gsub("widih(%p)","weh{wih}%1")

		:gsub("Weh( ?%.?%.?%.?) (%a)","Weh%1, %2")
		:gsub("([%a}\"\"]) weh([%s%p])","%1, weh%2")
		:gsub(" weh( ?%.?%.?%.?) (%a)"," weh%1, %2")

		:gsub("([Yy])a (ampun)","%1a{,} %2")
		:gsub("([Yy])a (Tuhan)","%1a{,} %2")
		:gsub("([Yy])a tuhan","%1a{,} Tuhan")
		:gsub("([Yy])a (iya)","%1a{,} %2")
		:gsub("Ya (sudah)","Ya{,} %1")
		:gsub(" ya (sudah)"," ya{,} %1")
		:gsub("([Yy])a (Allah)","%1a{,} %2")
		:gsub("([Yy])a (Gusti)","%1a{,} %2")
		:gsub("([Aa])ku ya aku","%1ku ya aku")
		:gsub("([Kk])amu ya kamu","%1amu ya kamu")
		:gsub("([Kk])au ya kau","%1amu ya kau")
		:gsub("([Dd])ia ya dia","%1ia ya dia")
		:gsub("([Kk])alian ya kalian","%1alian ya kalian")
		:gsub("([Mm])ereka ya mereka","%1ereka ya mereka")
		:gsub("([Kk])ita ya kita","%1ita ya kita")
		:gsub("([Kk])ami ya kami","%1ami ya kami")
		:gsub("(%u)(%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?) ya (%u)(%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?%a?)","%1%2{perlu koma?} {}ya %3%4")

		:gsub("ya ya ya","ya, ya, ya")
		:gsub(" ya yang"," ya{perlu koma?} yang")
		:gsub("Ya (%a)","Ya{perlu koma?} %1")
		:gsub("Ya( %.%.%.) (%a)","Ya%1{perlu koma?} %2")
		:gsub("([%a}\",]) ya([%s%p])","%1, ya%2")
		:gsub(" ya (%a)"," ya{perlu koma?} %1")
		:gsub(" ya( %.%.%.) (%a)"," ya%1{perlu koma?} %2")

		:gsub("Yah( ?%.?%.?%.?) (%a)","Yah%1, %2")
		:gsub("([%a}\",]) yah([%s%p])","%1, yah%2")
		:gsub(" yah( ?%.?%.?%.?) (%a)"," yah%1, %2")

		:gsub("Yo( ?%.?%.?%.?) (%a)","Yo%1, %2")
		:gsub("([%a}\"\"]) yo([%s%p])","%1, yo%2")
		:gsub(" yo( ?%.?%.?%.?) (%a)"," yo%1, %2")

		:gsub("Yuk( ?%.?%.?%.?) (%a)","Yuk%1, %2")
		:gsub("([%a}\"\"]) yuk([%s%p])","%1, yuk%2")
		:gsub(" yuk( ?%.?%.?%.?) (%a)"," yuk%1, %2")

		:gsub("Seh( ?%.?%.?%.?) (%a)","Sih{S(e)h}%1, %2")
		:gsub("([%a}\"\"]) seh([%s%p])","%1, sih{s(e)h}%2")
		:gsub(" seh( ?%.?%.?%.?) (%a)"," sih{s(e)h}%1, %2")

		:gsub("Sih( ?%.?%.?%.?) (%a)","Sih%1, %2")
		:gsub("([%a}\"\"]) sih([%s%p])","%1, sih%2")
		:gsub(" sih( ?%.?%.?%.?) (%a)"," sih%1, %2")
-- Wibunisasi
		:gsub("([Oo]nigiri)","%1{wibunisasi%: nasi kepal}")
		:gsub("{wibunisasi%: nasi kepal}{wibunisasi%: nasi kepal}","{wibunisasi%: nasi kepal}")
		:gsub("([Yy]akitori)","%1{wibunisasi%: sate ayam, ayam panggang}")
		:gsub("{wibunisasi%: sate ayam, ayam panggang}{wibunisasi%: sate ayam, ayam panggang}","{wibunisasi%: sate ayam, ayam panggang}")
		:gsub("([Nn]ikujaga)","%1{wibunisasi%: semur}")
		:gsub("{wibunisasi%: semur}{wibunisasi%: semur}","{wibunisasi%: semur}")
		:gsub("([Yy]akiniku)","%1{wibunisasi%: barbekyu, daging panggang}")
		:gsub("{wibunisasi%: barbekyu, daging panggang}{wibunisasi%: barbekyu, daging panggang}","{wibunisasi%: barbekyu, daging panggang}")
		:gsub("([Ss]enpai)","%1{wibunisasi%: Senior}")
		:gsub("{wibunisasi%: Senior}{wibunisasi%: Senior}","{wibunisasi%: Senior}")
		:gsub("([Kk]ohai)","%1{wibunisasi%: Junior}")
		:gsub("{wibunisasi%: Junior}{wibunisasi%: Junior}","{wibunisasi%: Junior}")
		:gsub("([Kk]ouhai)","%1{wibunisasi%: Junior}")
		:gsub("{wibunisasi%: Junior}{wibunisasi%: Junior}","{wibunisasi%: Junior}")
		:gsub("Moshi-moshi ","Halo, ")
		:gsub("Moshi-moshi","Halo")
		:gsub("moshi-moshi ","halo, ")
		:gsub("moshi-moshi","halo")
		:gsub("Ara(%p)","Wah%1")
		:gsub("Ara ","Wah, ")
		:gsub(" ara "," wah, ")
		:gsub(" ara(%p)"," wah%1")
		:gsub(" ara (%p)"," wah %1")
		:gsub("Are(%p)","Lo%1")
		:gsub("Are ","Lo, ")
		:gsub(" are "," lo, ")
		:gsub(" are(%p)"," lo%1")
		:gsub(" are (%p)"," lo %1")


-- Lain-lain
		:gsub("%!%?","%?%!{gue lebih suka yang %?%! ketimbang (%!)(%?) '3'}")
		:gsub("Ku ","\'Ku ")
		:gsub(" ku "," \'ku ")
		:gsub("Hirau","Hirau{= PEDULI, yakin pakai kata ini%?}")
		:gsub("hirau","hirau{= PEDULI, yakin pakai kata ini%?}")
		:gsub("Jadi ","Jadi{perlu koma%?} ")
		:gsub(" kalai "," kalau{kalai} ")
		:gsub("Kalai ","Kalau{Kalai} ")
		:gsub(" udah([%s%p])"," \'udah%1")
		:gsub("Udah","\'Udah")
		:gsub(" tlah([%s%p])"," t\'lah%1")
		:gsub("Tlah","T\'lah")
		:gsub("Ngomong-ngomong","Omong-ngomong{(Ng)omong-ngomong}")
		:gsub(", namun ",", tapi{\"namun\" untuk di awal kalimat} ")
		:gsub("([%l]) tapi ","%1, tapi ")
		:gsub("Tapi ","Tapi, ")
		:gsub("Tetapi, ","Namun{\"Tetapi\" untuk penghubung intrakalimat (di tengah kalimat)}, ")
		:gsub("Tetapi ","Namun{\"Tetapi\" untuk penghubung intrakalimat (di tengah kalimat)}, ")
		:gsub("senin([%s%p])","Senin{senin}%1")
		:gsub("selasa([%s%p])","Selasa{selasa}%1")
		:gsub("rabu([%s%p])","Rabu{rabu}%1")
		:gsub("kamis([%s%p])","Kamis{kamis}%1")
		:gsub("jumat([%s%p])","{jumat}Jumat%1")
		:gsub("jum\'at([%s%p])","Jumat{jum\'at}%1")
		:gsub("Jenius","Genius{(J)enius}")
		:gsub("jenius","genius{(j)enius}")
		:gsub(" Selamat Ulang Tahun"," Selamat Ulang Tahun")
		:gsub("Selamat Ulang Tahun","Selamat ulang tahun")
		:gsub(" Selamat Tahun Baru"," Selamat tahun baru")
		:gsub("Selamat Tahun Baru","Selamat tahun baru")
		:gsub("Frustasi","Frustrasi{Frustasi}")
		:gsub("frustasi","frustrasi{frustasi}")
		:gsub("Kubisa","Aku bisa{(Ku)bisa}")
		:gsub(" yang kubisa"," yang ku{}bisa")
		:gsub(" kubisa"," aku bisa{kubisa}")
		:gsub("Kaubisa","Kau bisa{Kaubisa}")
		:gsub(" yang kaubisa"," yang kau{}bisa")
		:gsub(" kaubisa"," kau bisa{(kau)bisa}")
		:gsub("([%a]) dll","%1, dll")
		:gsub("([%a]) dst","%1, dst")
		:gsub("([%a]) kah([%s%p])","%1kah{%1 kah}")
		:gsub("Anu %.%.%.%.","Anu, %.%.%.%.")

		:gsub("Kumasih([%s%pkmnalt][uyna]?)","Aku masih{Kumasih}%1")
		:gsub("kumasih([%s%pkmnalt][uyna]?)","aku masih{kumasih}%1")
		:gsub("Kaumasih([%s%pkmnalt][uyna]?)","Kau masih{Kaumasih}%1")
		:gsub("kaumasih([%s%pkmnalt][uyna]?)","kau masih{kaumasih}%1")
		:gsub("Kuingin([%s%pkmnalt][uyna]?)","Aku ingin{Kuingin}%1")
		:gsub("kuingin([%s%pkmnalt][uyna]?)","aku ingin{kuingin}%1")
		:gsub("Kauingin([%s%pkmnalt][uyna]?)","Kau ingin{Kauingin}%1")
		:gsub("kauingin([%s%pkmnalt][uyna]?)","kau ingin{kauingin}%1")
		:gsub("Takbisa([%s%pkmnalt][uyna]?)","Tak bisa{Takbisa}%1")
		:gsub("takbisa([%s%pkmnalt][uyna]?)","tak bisa{takbisa}%1")
		:gsub("Takapa([%s%pkmnalt][uyna]?)","Tak apa{Takapa}%1")
		:gsub("takapa([%s%pkmnalt][uyna]?)","tak apa{takapa}%1")
		:gsub("takdapat([%s%pkmnalt][uyna]?)","tak dapat{takdapat}%1")
		:gsub("Takdapat([%s%pkmnalt][uyna]?)","Tak dapat{Takdapat}%1")
		:gsub("Takmampu([%s%pkmnalt][uyna]?)","Tak mampu{Takmampu}%1")
		:gsub("takmampu([%s%pkmnalt][uyna]?)","tak mampu{takmampu}%1")
		:gsub("Takingin([%s%pkmnalt][uyna]?)","Tak ingin{Takingin}%1")
		:gsub("takingin([%s%pkmnalt][uyna]?)","tak ingin{takingin}%1")
		:gsub("Takpernah([%s%pkmnalt][uyna]?)","Tak pernah{Takpernah}%1")
		:gsub("takpernah([%s%pkmnalt][uyna]?)","tak pernah{takpernah}%1")
		:gsub("Takmerasa([%s%pkmnalt][uyna]?)","Tak merasa{Takmerasa}%1")
		:gsub("takmerasa([%s%pkmnalt][uyna]?)","tak merasa{takmerasa}%1")
		:gsub("Takperlu([%s%pkmnalt][uyna]?)","Tak perlu{Takperlu}%1")
		:gsub("takperlu([%s%pkmnalt][uyna]?)","tak perlu{takperlu}%1")
		:gsub("Takusah([%s%pkmnalt][uyna]?)","Tak usah{Takusah}%1")
		:gsub("takusah([%s%pkmnalt][uyna]?)","tak usah{takusah}%1")
		:gsub("Takkan([%s%pkmnalt][uyna]?)","Tak kan{Takkan}%1")
		:gsub("takkan([%s%pkmnalt][uyna]?)","tak kan{takkan}%1")
		:gsub("Takakan([%s%pkmnalt][uyna]?)","Tak akan{Takakan}%1")
		:gsub("takakan([%s%pkmnalt][uyna]?)","tak akan{takakan}%1")
		:gsub("Tak\'kan([%s%pkmnalt][uyna]?)","Tak \'kan{Tak\'kan}%1")
		:gsub("tak\'kan([%s%pkmnalt][uyna]?)","tak \'kan{tak\'kan}%1")
		:gsub("Takjumpa([%s%pkmnalt][uyna]?)","Tak jumpa{Takjumpa}%1")
		:gsub("takjumpa([%s%pkmnalt][uyna]?)","tak jumpa{takjumpa}%1")
		:gsub("Kumampu([%s%pkmnalt][uyna]?)","Ku mampu{Kumampu}%1")
		:gsub("Kaumampu([%s%pkmnalt][uyna]?)","Kau mampu{Kaumampu}%1")
		:gsub("Kuharuskan","Ku{}haruskan")
		:gsub("kuharuskan","ku{}haruskan")
		:gsub("Kuharus([%s%pkmnalt][uyna]?)","Aku harus{Kuharus}%1")
		:gsub("kuharus([%s%pkmnalt][uyna]?)","aku harus{kuharus}%1")
		:gsub("Kauharus([%s%pkmnalt][uyna]?)","Kau harus{Kauharus}%1")
		:gsub("kauharus([%s%pkmnalt][uyna]?)","kau harus{kauharus}%1")
		:gsub("Kumungkin ","Aku mungkin{Kumungkin} ")
		:gsub("kumungkin ","aku mungkin{kumungkin} ")
		:gsub("Kaumungkin ","Kau mungkin{Kaumungkin} ")
		:gsub("kaumungkin ","kau mungkin{kaumungkin} ")
		:gsub("Kupasti ","Aku pasti{Kupasti} ")
		:gsub("kupasti ","aku pasti{kupasti} ")
		:gsub("Kaupasti ","Kau pasti{Kaupasti} ")
		:gsub("kaupasti ","kau pasti{kaupasti} ")

		:gsub("Kutakluk","Ku{}takluk")
		:gsub(" kutakluk"," ku{}takluk")
		:gsub("Kutaksir","Ku{}taksir")
		:gsub(" kutaksir"," ku{}taksir")
		:gsub("Kutak","Aku tak{Kutak}")
		:gsub(" kutak"," aku tak{kutak}")
		:gsub("Kutaksir","Ku{}taksir")
		:gsub(" kutaksir"," ku{}taksir")
		:gsub("Kutaksir","Ku{}taksir")
		:gsub(" kutaksir"," ku{}taksir")
		:gsub("Kautak","Kau tak{(Kau)tak}")
		:gsub(" kautak"," kau tak{(kau)tak}")
		:gsub("Kumenangkan","Ku{}menangkan")
		:gsub(" kumenangkan"," ku{}menangkan")
		:gsub("Kaumenangkan","Kau{}menangkan")
		:gsub(" kaumenangkan"," kau{}menangkan")
		:gsub("Kume","Aku me{(Ku)me}")
		:gsub(" kume"," aku me{kume}")
		:gsub("Kaume","Kau me{(Kau)me}")
		:gsub(" kaume","kau me{(kau)me}")

		:gsub("^Tuk ","\'Tuk{Tuk} ")
		:gsub("%. Tuk ","%. \'Tuk{Tuk} ")
		:gsub(" tuk "," \'tuk{tuk} ")
		:gsub("(%p) tuk ","%1 \'tuk{tuk} ")
		:gsub("Karna ","Karena{Karna} ")
		:gsub(" karna "," karena{karna} ")
		:gsub("Tau ","Tahu{Tau} ")
		:gsub(" tau "," tahu{tau} ")
		:gsub("Nggak([%s%p])","Enggak{Nggak}%1")
		:gsub(" nggak([%s%p])"," enggak{nggak}%1")
		:gsub("Ga([%s%p])","Enggak{Ga}%1")
		:gsub(" ga([%s%p])"," enggak{ga}%1")
		:gsub("Ngga([%s%p])","Enggak{Ngga}%1")
		:gsub(" ngga([%s%p])"," enggak{ngga}%1")
		:gsub(" gak([%s%p])"," \'gak{gak}%1")
		:gsub("Gitu([%s%p])","\'Gitu{Gitu}%1")
		:gsub(" gitu([%s%p])"," \'gitu{gitu}%1")
		:gsub("Gini([%s%p])","\'Gini{Gini}%1")
		:gsub(" gini([%s%p])"," \'gini{gini}%1")
		:gsub("Sepotong kue([%s%p])","Sepotong kue{piece of cake = gampang}%1")
		:gsub(" sepotong kue([%s%p])"," sepotong kue{piece of cake = gampang}%1")
		:gsub("Kanan. Kamu benar([%s%p])","Kanan. Kamu benar{Yeah, you're right = Ya, kau benar}%1")
		:gsub("Kanan, kamu benar([%s%p])"," Kanan, kamu benar{Yeah, you're right = Ya, kau benar}%1")
		:gsub("Kamu([%s%p])","Kamu%1{gue jijik pakai kata ini, mending ubah jadi \"Kau\"}")
		:gsub(" kamu([%s%p])"," kamu%1{gue jijik pakai kata ini, mending ubah jadi \"kau\"}")
		:gsub("{gue jijik pakai kata ini, mending ubah jadi \"Kau\"}{gue jijik pakai kata ini, mending ubah jadi \"Kau\"}","{gue jijik pakai kata ini, mending ubah jadi \"Kau\"}")
		:gsub("{gue jijik pakai kata ini, mending ubah jadi \"kau\"}{gue jijik pakai kata ini, mending ubah jadi \"kau\"}","{gue jijik pakai kata ini, mending ubah jadi \"kau\"}")
		:gsub("\'Gimana([%s%p])","\'Gimana{Gimana}%1")
		:gsub(" \'gimana([%s%p])"," \'gimana{gimana}%1")
		:gsub(" tau "," tahu{tau} ")
		:gsub("Crepes","Krep{(Cre)pes}")
		:gsub("Crepe","Krep{(Cre)pe}")
		:gsub("Yg([%s%p])","Yang{Yg}%1")
		:gsub(" yg([%s%p])"," yang{yg}%1")
		:gsub("crepes","krep{(cre)pes}")
		:gsub("crepe","krep{(cre)pe}")
		:gsub("Gw([%s%pkmnalt][uyna]?)","Gue{Gw}%1")
		:gsub("gw([%s%pkmnalt][uyna]?)","gue{gw}%1")
		:gsub("baharu([%s%pkmnalt][uyna]?)","baru{baharu}%1")
		:gsub("Blanko([%s%pkmnalt][uyna]?)","Blangko{Blanko}%1")
		:gsub("blanko([%s%pkmnalt][uyna]?)","blangko{blanko}%1")
		:gsub("Website([%s%pkmnalt][uyna]?)","Situs web{Website}%1")
		:gsub("website([%s%pkmnalt][uyna]?)","situs web{website}%1")
		:gsub("E%-mail([%s%pkmnalt][uyna]?)","Surel{E-mail}%1")
		:gsub("e%-mail([%s%pkmnalt][uyna]?)","surel{e-mail}%1")
		:gsub("Email([%s%pkmnalt][uyna]?)","Surel{Email}%1")
		:gsub("email([%s%pkmnalt][uyna]?)","surel{email}%1")
		:gsub("Megabyte([%s%p])","Megabit{Megabyte}%1")
		:gsub("Gigabyte([%s%p])","Gigabit{Gigabyte}%1")
		:gsub("Chip([%s%p])","Cip{Chip}%1")
		:gsub("chip([%s%p])","cip{chip}%1")
		:gsub("Browsing([%s%p])","Berselancar{Browsing}%1")
		:gsub("browsing([%s%p])","berselancar{browsing}%1")
		:gsub("Filem([%s%pkmnalt][uyna]?)","Film{Filem}%1")
		:gsub("filem([%s%pkmnalt][uyna]?)","film{filem}%1")
		:gsub("Error([%s%pkmnalt][uyna]?)","Galat{Error}%1")
		:gsub("error([%s%pkmnalt][uyna]?)","galat{error}%1")
		:gsub("Install([%s%pkmnalt][uyna]?)","Instal{Install}%1")
		:gsub("install([%s%pkmnalt][uyna]?)","instal{install}%1")
		:gsub("Tehnologi([%s%pkmnalt][uyna]?)","Teknologi{Tehnologi}%1")
		:gsub("tehnologi([%s%pkmnalt][uyna]?)","teknologi{tehnologi}%1")
		:gsub("File([%s%pkmnalt][uyna]?)","Berkas{File}%1")
		:gsub("file([%s%pkmnalt][uyna]?)","berkas{file}%1")
		:gsub("([Mm])en-download","%1engunduh{%1en-down(load)}")
		:gsub("([Mm])en-{\\i1}download{\\i0}","%1engunduh{%1en-down(load)}")
		:gsub("([Mm])en-upload","%1enguggah{%1eng-up(load)}")
		:gsub("([Mm])en-{\\i1}upload{\\i0}","%1enguggah{%1eng-up(load)}")
		:gsub("([Mm])endownload","%1engunduh{%1endown(load)}")
		:gsub("([Mm])en{\\i1}download{\\i0}","%1engunduh{%1endown(load)}")
		:gsub("([Mm])engupload","%1enguggah{%1engup(load)}")
		:gsub("([Mm])en{\\i1}upload{\\i0}","%1enguggah{%1engup(load)}")
		:gsub("Seterah([%s%p])","Terserah{Seterah}")
		:gsub("seterah([%s%p])","terserah{seterah}")
		:gsub("Belom([%s%p])","Belum{Belom}%1")
		:gsub("belom([%s%p])","belum{belom}%1")
		:gsub(" islam([%s%p])"," Islam{ islam}%1")
		:gsub(" kristen([%s%p])"," Kristen{ kristen}%1")
		:gsub(" katholik([%s%p])"," Katolik{ katholik}%1")
		:gsub(" katolik([%s%p])"," Katolik{ katolik}%1")
		:gsub(" hindu([%s%p])"," Hindu{ hindu}%1")
		:gsub(" buddha([%s%p])"," Buddha{ buddha}%1")
		:gsub(" budha([%s%p])"," Buddha{ budha}%1")
		:gsub(" Budha([%s%p])"," Buddha{ Budha}%1")
		:gsub("Translator([%s%p])","Penerjemah{Translator}%1%1")
		:gsub("translator([%s%p])","penerjemah{translator}")
		:gsub("Translation([%s%p])","Penerjemah{Translation}%1")
		:gsub("translation([%s%p])","penerjemah{translation}%1")
		:gsub("Translations([%s%p])","Penerjemah{Translations}%1")
		:gsub("translations([%s%p])","penerjemah{translations}%1")
		:gsub("TLC([%s%p])","Pemeriksa Terjemahan{TLC}%1")
		:gsub("tlc([%s%p])","pemeriksa terjemahan{tlc}%1")
		:gsub("Editing([%s%p])","Editor{Editing}%1")
		:gsub("editing([%s%p])","editor{editing}%1")
		:gsub("Editor %: (%a)","Editor %: EditorTampan{Max FireHeart}, %1")
		:gsub("editor %: (%a)","editor %: EditorTampan{Max FireHeart}, %1")
		:gsub("Editor%: (%a)","Editor%: EditorTampan{Max FireHeart}, %1")
		:gsub("editor%: (%a)","editor%: EditorTampan{Max FireHeart}, %1")
		:gsub("Penyunting %: (%a)","Editor %: EditorTampan{Max FireHeart}, %1")
		:gsub("penyunting %: (%a)","editor %: EditorTampan{Max FireHeart}, %1")
		:gsub("Penyunting%: (%a)","Editor%: EditorTampan{Max FireHeart}, %1")
		:gsub("penyunting%: (%a)","editor%: EditorTampan{Max FireHeart}, %1")
		:gsub("Typesetter([%s%p])","Penata Rias{Typesetter}%1")
		:gsub("typesetter([%s%p])","penata rias{typesetter}%1")
		:gsub("Typesett([%s%p])","Penata Rias{Typesett}%1")
		:gsub("typesett([%s%p])","penata rias{typesett}%1")
		:gsub("Typesetting([%s%p])","Penata Rias{Typesetting}%1")
		:gsub("typesetting([%s%p])","penata rias{typesetting}%1")
		:gsub("Timer([%s%p])","Pewaktu{Pengatur Waktu}%1")
		:gsub("timer([%s%p])","pewaktu rias{pengatur waktu}%1")
		:gsub("Timing([%s%p])","Pengatur Waktu{Pewaktu}%1")
		:gsub("timing([%s%p])","pengatur waktu{pewaktu}%1")
		:gsub("Encode%+Upload([%s%p])","Pengolah Video dan Pengunggah{Encode%+Upload}%1")
		:gsub("encode%+upload([%s%p])","pengolah video dan pengunggah{encode%+upload}%1")
		:gsub("Encode %+ Upload([%s%p])","Pengolah Video dan Pengunggah{Encode %+ Upload}%1")
		:gsub("encode %+ upload([%s%p])","pengolah video dan pengunggah{encode %+ upload}%1")
		:gsub("Encoder%+Uploader([%s%p])","Pengolah Video dan Pengunggah{Encoder%+Uploader}%1")
		:gsub("encoder%+uploader([%s%p])","pengolah video dan pengunggah{encoder%+uploader}%1")
		:gsub("Encoder %+ Uploader([%s%p])","Pengolah Video dan Pengunggah{Encoder %+ Uploader}%1")
		:gsub("encoder %+ uploader([%s%p])","pengolah video dan pengunggah{encoder %+ uploader}%1")

		:gsub("Encode%&Upload([%s%p])","Pengolah Video dan Pengunggah{Encode%&Upload}%1")
		:gsub("encode%&upload([%s%p])","pengolah video dan pengunggah{encode%&upload}%1")
		:gsub("Encode %& Upload([%s%p])","Pengolah Video dan Pengunggah{Encode %& Upload}%1")
		:gsub("encode %& upload([%s%p])","pengolah video dan pengunggah{encode %& upload}%1")
		:gsub("Encoder%&Uploader([%s%p])","Pengolah Video dan Pengunggah{Encoder%&Uploader}%1")
		:gsub("encoder%&uploader([%s%p])","pengolah video dan pengunggah{encoder%&uploader}%1")
		:gsub("Encoder %& Uploader([%s%p])","Pengolah Video dan Pengunggah{Encoder %& Uploader}%1")
		:gsub("encoder %& uploader([%s%p])","pengolah video dan pengunggah{encoder %& uploader}%1")

		:gsub("Encode([%s%p])","Pengolah Video{Encode}%1")
		:gsub("encode([%s%p])","pengolah video{encode}%1")
		:gsub("Encoder([%s%p])","Pengolah Video{Encoder}%1")
		:gsub("encoder([%s%p])","pengolah video{encoder}%1")

		:gsub("Uploader([%s%p])","Pengunggah{Up(load)er}%1")
		:gsub("uploader([%s%p])","pengunggah{up(load)er}%1")
		:gsub("Download","Unduh{Download}")
		:gsub("download","unduh{download}")
		:gsub("Upload","Unduh{Upload}")
		:gsub("upload","unggah{upload}")

		:gsub("QC([%s%p])","Pemeriksa Akhir{QC}%1")
		:gsub("QC\'er([%s%p])","Pemeriksa Akhir{QC\'er}%1")
		:gsub("QualityChecker([%s%p])","Pemeriksa Akhir{QualityChecker}%1")
		:gsub("Quality Checker([%s%p])","Pemeriksa Akhir{Quality Checker}%1")
		:gsub("qualitychecker([%s%p])","pemeriksa akhir{qualitychecker}%1")
		:gsub("quality checker([%s%p])","pemeriksa akhir{quality checker}%1")

		:gsub("QualityCheck([%s%p])","Pemeriksa Akhir{QualityCheck}%1")
		:gsub("Quality Check([%s%p])","Pemeriksa Akhir{Quality Check}%1")
		:gsub("qualitycheck([%s%p])","pemeriksa akhir{qualitycheck}%1")
		:gsub("quality check([%s%p])","pemeriksa akhir{quality check}%1")

		:gsub("Timing([%s%p])","Pengatur Waktu{Pewaktu}%1")
		:gsub("timing([%s%p])","pengatur waktu{pewaktu}%1")
		:gsub("TS([%s%p])","Penata Rias{TS}%1")
		:gsub("TSer([%s%p])","Penata Rias{TSer}%1")
		:gsub("TS\'er([%s%p])","Penata Rias{TS\'er}%1")
		:gsub("Pt%. ","Bag%.{Pt. } ")
		:gsub("pt%. ","bag%.{pt. } ")
		:gsub(", jadi,",", jadi")
		:gsub(" aja([%s%p])"," \'aja%1")
		:gsub("Enggak{Ga}%-","Ga%-")
		:gsub("Enggak{Ga} ","Ga ")
		:gsub("yang mulia","yang mulia{kalau ini sebagai kata sapaan, tulisannya jadi \"Yang Mulia\"}")
		:gsub("{kalau ini sebagai kata sapaan, tulisannya jadi \"Yang Mulia\"}{kalau ini sebagai kata sapaan, tulisannya jadi \"Yang Mulia\"}","{kalau ini sebagai kata sapaan, tulisannya jadi \"Yang Mulia\"}")
		:gsub(" ya%."," ya%.{kalau ini kalimat tanya, kasih tanda tanya}")
		:gsub(" ya %.%.%.%."," ya %.%.%.%.{kalau ini kalimat tanya, kasih tanda tanya}")
		:gsub("(%([^\\()]-%))(%([^\\()]-%))","%1")
		:gsub("(%{[^\\{}]-%})(%([^\\()]-%))","%2")

		:gsub("{([^\\{]-){([^\\}]-)}}","{%2}")
		:gsub("{([^\\{}]-){([^\\}]-)}([^\\{}]-)}","{%1(x%2q)%3}")
		:gsub("{([^\\{}]-){([^\\}]-)}([^\\{}]-){([^\\}]-)}([^\\{}]-)}","{%1(x%2q)%3(x%4q)%5}")
		:gsub("{([^\\}]-)}([^\\{}]-)}","(x%1q)%2")
		:gsub("(%([^\\()]-%))(%([^\\()]-%))","%1")

		:gsub("{}","")
		:gsub("}}","}")
		:gsub("}}","}")
		:gsub(",,",",")
		:gsub(",\",",",\"")
		:gsub("\'\'","\'")
		:gsub(",\"{[^}]-},",",\"")
		:gsub("(%d%d)/(%d%d)/(%d%d%d?%d?)","%1%-%2%-%3{Ini urutan tanggal dan bulannya kebalik, 'gak? Urutannya: tanggal-bulan-tahun}")
		:gsub("%.%.%. (%p)","%.%.%.%1")
		:gsub("%.%.%.(\"%a)","%.%.%. %1")
		:gsub("([%a%p]) %.%.%., %.%.%.","%1, %.%.%.")
		:gsub("%.({[^\\}]-}),","%.%1")
		:gsub("([%a])%.,","%1%.")
		
		:gsub("^(%.%.) ","%.%.%. ")
		:gsub(" %.%. "," %.%.%. ")
		:gsub(" (%.%.)$"," %.%.%.")
		:gsub(" %.%.%?"," %.%.%.%?")
		:gsub(" %.%.%!"," %.%.%.%!")
		:gsub("{,}{,}","{,}")
		:gsub("{,},",",")
		:gsub("%?%?","?")
		:gsub(" %.%. "," %.%.%. ")
		:gsub(" (%.%.)$"," %.%1")
		:gsub("%.%.%.%.%.","%.%.%.")
		:gsub("([%a%p]) %.%.%.\\N([%a%p])","%1 %.%.%. \\N%2")
		:gsub(" xxN","\\N")
		:gsub("  ([%s]?)"," ")
		:gsub("^\\N([%a])","%.%.%. \\N%1")
		:gsub("}%.%.%. m","}m")
		:gsub("kan%?%.%.%.","kan%?")
		:gsub(",, kan",", kan")
		:gsub("}%(x([%a%s%p])",",}{(x%1")
		:gsub("([%a%s%p]){q%),","%1}{q%),")
		:gsub("}}{q","}{q")
		:gsub("(xq)","")
		:gsub("%? %?","%?")
		:gsub("(%a)%.,","%1%.")
		:gsub(",, %.%.%.",", %.%.%.")
		:gsub("({\\[^}]-}) %.%.%. ","%1%.%.%. ")
		:gsub("} %.%.%. (m %d)","}%1")
		:gsub("(%l%.)%.$","%1")
		:gsub("(}%.)%.$","%1")
		:gsub("%.(%a)","%. %1")
		:gsub(" gak \'gak"," \'gak \'gak")
		:gsub("{Perlu elipsis%?} %.%.%. \"","{Perlu elipsis%?}\"")
		:gsub("^%.%.%.\'","%.%.%. \'")
		:gsub("%.%.%.%.(%a)","%.%.%. %1")
		:gsub("%?%.%.%.","%.%.%.%?")
		:gsub("%? %.%.%.","%.%.%. %?")
		:gsub("(%a) %. (%a)","%1%. %2")
		:gsub("(%a) ({[^}]-})$","%1 %.%.% %2")
		:gsub("(%a) %.({[^}]-})","%1%.%2")
		:gsub("(%a) %.%.({[^}]-})","%1 %.%.%.%2")
		:gsub(" %.%. (%a)"," %.%.%. %1")
		:gsub("\"%.%. (%a)","\"%.%.%. %1")
		:gsub("(%a)%.%.({[^}]-})","%1%.%2")
		:gsub("%.({[^}]-})%.","%.%1")
		:gsub("%(x q%)"," ")
		:gsub(", %.%.%.,",",")
	line.text=text
        subs[i]=line
    end
    aegisub.set_undo_point(script_name)
    return sel
end

aegisub.register_macro(script_name, script_description, tampan)